/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the UserDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserDataAttributes{}

// UserDataAttributes struct for UserDataAttributes
type UserDataAttributes struct {
	// unique username
	Username string `json:"username"`
	// display name
	Pseudonym *string `json:"pseudonym,omitempty"`
	// user bio
	Description *string `json:"description,omitempty"`
	// resolved URL of the user's avatar, if one is set
	AvatarUrl *string `json:"avatar_url,omitempty"`
	// The role assigned to the user
	Role string `json:"role"`
	// The version number of the user record
	Version int32 `json:"version"`
	// The date and time when the user was created
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the user was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _UserDataAttributes UserDataAttributes

// NewUserDataAttributes instantiates a new UserDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDataAttributes(username string, role string, version int32, createdAt time.Time, updatedAt time.Time) *UserDataAttributes {
	this := UserDataAttributes{}
	this.Username = username
	this.Role = role
	this.Version = version
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewUserDataAttributesWithDefaults instantiates a new UserDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDataAttributesWithDefaults() *UserDataAttributes {
	this := UserDataAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *UserDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetPseudonym returns the Pseudonym field value if set, zero value otherwise.
func (o *UserDataAttributes) GetPseudonym() string {
	if o == nil || IsNil(o.Pseudonym) {
		var ret string
		return ret
	}
	return *o.Pseudonym
}

// GetPseudonymOk returns a tuple with the Pseudonym field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetPseudonymOk() (*string, bool) {
	if o == nil || IsNil(o.Pseudonym) {
		return nil, false
	}
	return o.Pseudonym, true
}

// HasPseudonym returns a boolean if a field has been set.
func (o *UserDataAttributes) HasPseudonym() bool {
	if o != nil && !IsNil(o.Pseudonym) {
		return true
	}

	return false
}

// SetPseudonym gets a reference to the given string and assigns it to the Pseudonym field.
func (o *UserDataAttributes) SetPseudonym(v string) {
	o.Pseudonym = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UserDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UserDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UserDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *UserDataAttributes) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *UserDataAttributes) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *UserDataAttributes) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetRole returns the Role field value
func (o *UserDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UserDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetVersion returns the Version field value
func (o *UserDataAttributes) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *UserDataAttributes) SetVersion(v int32) {
	o.Version = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o UserDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if !IsNil(o.Pseudonym) {
		toSerialize["pseudonym"] = o.Pseudonym
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	toSerialize["role"] = o.Role
	toSerialize["version"] = o.Version
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *UserDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"role",
		"version",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserDataAttributes := _UserDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserDataAttributes)

	if err != nil {
		return err
	}

	*o = UserDataAttributes(varUserDataAttributes)

	return err
}

type NullableUserDataAttributes struct {
	value *UserDataAttributes
	isSet bool
}

func (v NullableUserDataAttributes) Get() *UserDataAttributes {
	return v.value
}

func (v *NullableUserDataAttributes) Set(val *UserDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDataAttributes(val *UserDataAttributes) *NullableUserDataAttributes {
	return &NullableUserDataAttributes{value: val, isSet: true}
}

func (v NullableUserDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
