/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/google/uuid"
)

// checks if the DeleteUploadUserAvatarData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadUserAvatarData{}

// DeleteUploadUserAvatarData struct for DeleteUploadUserAvatarData
type DeleteUploadUserAvatarData struct {
	// user id
	Id         uuid.UUID                            `json:"id"`
	Type       string                               `json:"type"`
	Attributes DeleteUploadUserAvatarDataAttributes `json:"attributes"`
}

type _DeleteUploadUserAvatarData DeleteUploadUserAvatarData

// NewDeleteUploadUserAvatarData instantiates a new DeleteUploadUserAvatarData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadUserAvatarData(id uuid.UUID, type_ string, attributes DeleteUploadUserAvatarDataAttributes) *DeleteUploadUserAvatarData {
	this := DeleteUploadUserAvatarData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDeleteUploadUserAvatarDataWithDefaults instantiates a new DeleteUploadUserAvatarData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadUserAvatarDataWithDefaults() *DeleteUploadUserAvatarData {
	this := DeleteUploadUserAvatarData{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteUploadUserAvatarData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadUserAvatarData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteUploadUserAvatarData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DeleteUploadUserAvatarData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadUserAvatarData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeleteUploadUserAvatarData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DeleteUploadUserAvatarData) GetAttributes() DeleteUploadUserAvatarDataAttributes {
	if o == nil {
		var ret DeleteUploadUserAvatarDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadUserAvatarData) GetAttributesOk() (*DeleteUploadUserAvatarDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DeleteUploadUserAvatarData) SetAttributes(v DeleteUploadUserAvatarDataAttributes) {
	o.Attributes = v
}

func (o DeleteUploadUserAvatarData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadUserAvatarData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DeleteUploadUserAvatarData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadUserAvatarData := _DeleteUploadUserAvatarData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadUserAvatarData)

	if err != nil {
		return err
	}

	*o = DeleteUploadUserAvatarData(varDeleteUploadUserAvatarData)

	return err
}

type NullableDeleteUploadUserAvatarData struct {
	value *DeleteUploadUserAvatarData
	isSet bool
}

func (v NullableDeleteUploadUserAvatarData) Get() *DeleteUploadUserAvatarData {
	return v.value
}

func (v *NullableDeleteUploadUserAvatarData) Set(val *DeleteUploadUserAvatarData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadUserAvatarData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadUserAvatarData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadUserAvatarData(val *DeleteUploadUserAvatarData) *NullableDeleteUploadUserAvatarData {
	return &NullableDeleteUploadUserAvatarData{value: val, isSet: true}
}

func (v NullableDeleteUploadUserAvatarData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadUserAvatarData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
