/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UploadUserMediaLinksDataAttributesAvatar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadUserMediaLinksDataAttributesAvatar{}

// UploadUserMediaLinksDataAttributesAvatar struct for UploadUserMediaLinksDataAttributesAvatar
type UploadUserMediaLinksDataAttributesAvatar struct {
	// Key for the avatar in the storage service
	Key string `json:"key"`
	// Pre-signed URL for uploading the avatar
	UploadUrl string `json:"upload_url"`
	// URL for preloading the avatar after upload
	PreloadUrl string `json:"preload_url"`
}

type _UploadUserMediaLinksDataAttributesAvatar UploadUserMediaLinksDataAttributesAvatar

// NewUploadUserMediaLinksDataAttributesAvatar instantiates a new UploadUserMediaLinksDataAttributesAvatar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadUserMediaLinksDataAttributesAvatar(key string, uploadUrl string, preloadUrl string) *UploadUserMediaLinksDataAttributesAvatar {
	this := UploadUserMediaLinksDataAttributesAvatar{}
	this.Key = key
	this.UploadUrl = uploadUrl
	this.PreloadUrl = preloadUrl
	return &this
}

// NewUploadUserMediaLinksDataAttributesAvatarWithDefaults instantiates a new UploadUserMediaLinksDataAttributesAvatar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadUserMediaLinksDataAttributesAvatarWithDefaults() *UploadUserMediaLinksDataAttributesAvatar {
	this := UploadUserMediaLinksDataAttributesAvatar{}
	return &this
}

// GetKey returns the Key field value
func (o *UploadUserMediaLinksDataAttributesAvatar) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinksDataAttributesAvatar) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UploadUserMediaLinksDataAttributesAvatar) SetKey(v string) {
	o.Key = v
}

// GetUploadUrl returns the UploadUrl field value
func (o *UploadUserMediaLinksDataAttributesAvatar) GetUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinksDataAttributesAvatar) GetUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadUrl, true
}

// SetUploadUrl sets field value
func (o *UploadUserMediaLinksDataAttributesAvatar) SetUploadUrl(v string) {
	o.UploadUrl = v
}

// GetPreloadUrl returns the PreloadUrl field value
func (o *UploadUserMediaLinksDataAttributesAvatar) GetPreloadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreloadUrl
}

// GetPreloadUrlOk returns a tuple with the PreloadUrl field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinksDataAttributesAvatar) GetPreloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreloadUrl, true
}

// SetPreloadUrl sets field value
func (o *UploadUserMediaLinksDataAttributesAvatar) SetPreloadUrl(v string) {
	o.PreloadUrl = v
}

func (o UploadUserMediaLinksDataAttributesAvatar) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadUserMediaLinksDataAttributesAvatar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["upload_url"] = o.UploadUrl
	toSerialize["preload_url"] = o.PreloadUrl
	return toSerialize, nil
}

func (o *UploadUserMediaLinksDataAttributesAvatar) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"upload_url",
		"preload_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadUserMediaLinksDataAttributesAvatar := _UploadUserMediaLinksDataAttributesAvatar{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadUserMediaLinksDataAttributesAvatar)

	if err != nil {
		return err
	}

	*o = UploadUserMediaLinksDataAttributesAvatar(varUploadUserMediaLinksDataAttributesAvatar)

	return err
}

type NullableUploadUserMediaLinksDataAttributesAvatar struct {
	value *UploadUserMediaLinksDataAttributesAvatar
	isSet bool
}

func (v NullableUploadUserMediaLinksDataAttributesAvatar) Get() *UploadUserMediaLinksDataAttributesAvatar {
	return v.value
}

func (v *NullableUploadUserMediaLinksDataAttributesAvatar) Set(val *UploadUserMediaLinksDataAttributesAvatar) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadUserMediaLinksDataAttributesAvatar) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadUserMediaLinksDataAttributesAvatar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadUserMediaLinksDataAttributesAvatar(val *UploadUserMediaLinksDataAttributesAvatar) *NullableUploadUserMediaLinksDataAttributesAvatar {
	return &NullableUploadUserMediaLinksDataAttributesAvatar{value: val, isSet: true}
}

func (v NullableUploadUserMediaLinksDataAttributesAvatar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadUserMediaLinksDataAttributesAvatar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
