/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/google/uuid"
)

// checks if the UpdateUserData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUserData{}

// UpdateUserData struct for UpdateUserData
type UpdateUserData struct {
	// user id
	Id         uuid.UUID                `json:"id"`
	Type       string                   `json:"type"`
	Attributes UpdateUserDataAttributes `json:"attributes"`
}

type _UpdateUserData UpdateUserData

// NewUpdateUserData instantiates a new UpdateUserData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserData(id uuid.UUID, type_ string, attributes UpdateUserDataAttributes) *UpdateUserData {
	this := UpdateUserData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateUserDataWithDefaults instantiates a new UpdateUserData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserDataWithDefaults() *UpdateUserData {
	this := UpdateUserData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateUserData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateUserData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateUserData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateUserData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateUserData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateUserData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateUserData) GetAttributes() UpdateUserDataAttributes {
	if o == nil {
		var ret UpdateUserDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateUserData) GetAttributesOk() (*UpdateUserDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateUserData) SetAttributes(v UpdateUserDataAttributes) {
	o.Attributes = v
}

func (o UpdateUserData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUserData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateUserData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateUserData := _UpdateUserData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateUserData)

	if err != nil {
		return err
	}

	*o = UpdateUserData(varUpdateUserData)

	return err
}

type NullableUpdateUserData struct {
	value *UpdateUserData
	isSet bool
}

func (v NullableUpdateUserData) Get() *UpdateUserData {
	return v.value
}

func (v *NullableUpdateUserData) Set(val *UpdateUserData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserData(val *UpdateUserData) *NullableUpdateUserData {
	return &NullableUpdateUserData{value: val, isSet: true}
}

func (v NullableUpdateUserData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
