/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"encoding/json"
)

// checks if the DeleteUploadUserAvatarDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadUserAvatarDataAttributes{}

// DeleteUploadUserAvatarDataAttributes struct for DeleteUploadUserAvatarDataAttributes
type DeleteUploadUserAvatarDataAttributes struct {
	// avatar media key
	AvatarKey *string `json:"avatar_key,omitempty"`
}

// NewDeleteUploadUserAvatarDataAttributes instantiates a new DeleteUploadUserAvatarDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadUserAvatarDataAttributes() *DeleteUploadUserAvatarDataAttributes {
	this := DeleteUploadUserAvatarDataAttributes{}
	return &this
}

// NewDeleteUploadUserAvatarDataAttributesWithDefaults instantiates a new DeleteUploadUserAvatarDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadUserAvatarDataAttributesWithDefaults() *DeleteUploadUserAvatarDataAttributes {
	this := DeleteUploadUserAvatarDataAttributes{}
	return &this
}

// GetAvatarKey returns the AvatarKey field value if set, zero value otherwise.
func (o *DeleteUploadUserAvatarDataAttributes) GetAvatarKey() string {
	if o == nil || IsNil(o.AvatarKey) {
		var ret string
		return ret
	}
	return *o.AvatarKey
}

// GetAvatarKeyOk returns a tuple with the AvatarKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteUploadUserAvatarDataAttributes) GetAvatarKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarKey) {
		return nil, false
	}
	return o.AvatarKey, true
}

// HasAvatarKey returns a boolean if a field has been set.
func (o *DeleteUploadUserAvatarDataAttributes) HasAvatarKey() bool {
	if o != nil && !IsNil(o.AvatarKey) {
		return true
	}

	return false
}

// SetAvatarKey gets a reference to the given string and assigns it to the AvatarKey field.
func (o *DeleteUploadUserAvatarDataAttributes) SetAvatarKey(v string) {
	o.AvatarKey = &v
}

func (o DeleteUploadUserAvatarDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadUserAvatarDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarKey) {
		toSerialize["avatar_key"] = o.AvatarKey
	}
	return toSerialize, nil
}

type NullableDeleteUploadUserAvatarDataAttributes struct {
	value *DeleteUploadUserAvatarDataAttributes
	isSet bool
}

func (v NullableDeleteUploadUserAvatarDataAttributes) Get() *DeleteUploadUserAvatarDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadUserAvatarDataAttributes) Set(val *DeleteUploadUserAvatarDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadUserAvatarDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadUserAvatarDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadUserAvatarDataAttributes(val *DeleteUploadUserAvatarDataAttributes) *NullableDeleteUploadUserAvatarDataAttributes {
	return &NullableDeleteUploadUserAvatarDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadUserAvatarDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadUserAvatarDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
