/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QRConfirmData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QRConfirmData{}

// QRConfirmData struct for QRConfirmData
type QRConfirmData struct {
	Type       string                  `json:"type"`
	Attributes QRConfirmDataAttributes `json:"attributes"`
}

type _QRConfirmData QRConfirmData

// NewQRConfirmData instantiates a new QRConfirmData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQRConfirmData(type_ string, attributes QRConfirmDataAttributes) *QRConfirmData {
	this := QRConfirmData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewQRConfirmDataWithDefaults instantiates a new QRConfirmData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQRConfirmDataWithDefaults() *QRConfirmData {
	this := QRConfirmData{}
	return &this
}

// GetType returns the Type field value
func (o *QRConfirmData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QRConfirmData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QRConfirmData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *QRConfirmData) GetAttributes() QRConfirmDataAttributes {
	if o == nil {
		var ret QRConfirmDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *QRConfirmData) GetAttributesOk() (*QRConfirmDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *QRConfirmData) SetAttributes(v QRConfirmDataAttributes) {
	o.Attributes = v
}

func (o QRConfirmData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QRConfirmData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *QRConfirmData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQRConfirmData := _QRConfirmData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQRConfirmData)

	if err != nil {
		return err
	}

	*o = QRConfirmData(varQRConfirmData)

	return err
}

type NullableQRConfirmData struct {
	value *QRConfirmData
	isSet bool
}

func (v NullableQRConfirmData) Get() *QRConfirmData {
	return v.value
}

func (v *NullableQRConfirmData) Set(val *QRConfirmData) {
	v.value = val
	v.isSet = true
}

func (v NullableQRConfirmData) IsSet() bool {
	return v.isSet
}

func (v *NullableQRConfirmData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQRConfirmData(val *QRConfirmData) *NullableQRConfirmData {
	return &NullableQRConfirmData{value: val, isSet: true}
}

func (v NullableQRConfirmData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQRConfirmData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
