/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UploadUserMediaLinksDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadUserMediaLinksDataAttributes{}

// UploadUserMediaLinksDataAttributes struct for UploadUserMediaLinksDataAttributes
type UploadUserMediaLinksDataAttributes struct {
	Avatar UploadUserMediaLinksDataAttributesAvatar `json:"avatar"`
}

type _UploadUserMediaLinksDataAttributes UploadUserMediaLinksDataAttributes

// NewUploadUserMediaLinksDataAttributes instantiates a new UploadUserMediaLinksDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadUserMediaLinksDataAttributes(avatar UploadUserMediaLinksDataAttributesAvatar) *UploadUserMediaLinksDataAttributes {
	this := UploadUserMediaLinksDataAttributes{}
	this.Avatar = avatar
	return &this
}

// NewUploadUserMediaLinksDataAttributesWithDefaults instantiates a new UploadUserMediaLinksDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadUserMediaLinksDataAttributesWithDefaults() *UploadUserMediaLinksDataAttributes {
	this := UploadUserMediaLinksDataAttributes{}
	return &this
}

// GetAvatar returns the Avatar field value
func (o *UploadUserMediaLinksDataAttributes) GetAvatar() UploadUserMediaLinksDataAttributesAvatar {
	if o == nil {
		var ret UploadUserMediaLinksDataAttributesAvatar
		return ret
	}

	return o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinksDataAttributes) GetAvatarOk() (*UploadUserMediaLinksDataAttributesAvatar, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Avatar, true
}

// SetAvatar sets field value
func (o *UploadUserMediaLinksDataAttributes) SetAvatar(v UploadUserMediaLinksDataAttributesAvatar) {
	o.Avatar = v
}

func (o UploadUserMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadUserMediaLinksDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["avatar"] = o.Avatar
	return toSerialize, nil
}

func (o *UploadUserMediaLinksDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"avatar",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadUserMediaLinksDataAttributes := _UploadUserMediaLinksDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadUserMediaLinksDataAttributes)

	if err != nil {
		return err
	}

	*o = UploadUserMediaLinksDataAttributes(varUploadUserMediaLinksDataAttributes)

	return err
}

type NullableUploadUserMediaLinksDataAttributes struct {
	value *UploadUserMediaLinksDataAttributes
	isSet bool
}

func (v NullableUploadUserMediaLinksDataAttributes) Get() *UploadUserMediaLinksDataAttributes {
	return v.value
}

func (v *NullableUploadUserMediaLinksDataAttributes) Set(val *UploadUserMediaLinksDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadUserMediaLinksDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadUserMediaLinksDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadUserMediaLinksDataAttributes(val *UploadUserMediaLinksDataAttributes) *NullableUploadUserMediaLinksDataAttributes {
	return &NullableUploadUserMediaLinksDataAttributes{value: val, isSet: true}
}

func (v NullableUploadUserMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadUserMediaLinksDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
