/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/google/uuid"
)

// checks if the UserSessionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSessionData{}

// UserSessionData struct for UserSessionData
type UserSessionData struct {
	// session id
	Id         uuid.UUID             `json:"id"`
	Type       string                `json:"type"`
	Attributes UserSessionAttributes `json:"attributes"`
}

type _UserSessionData UserSessionData

// NewUserSessionData instantiates a new UserSessionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSessionData(id uuid.UUID, type_ string, attributes UserSessionAttributes) *UserSessionData {
	this := UserSessionData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUserSessionDataWithDefaults instantiates a new UserSessionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSessionDataWithDefaults() *UserSessionData {
	this := UserSessionData{}
	return &this
}

// GetId returns the Id field value
func (o *UserSessionData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserSessionData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserSessionData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UserSessionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UserSessionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UserSessionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UserSessionData) GetAttributes() UserSessionAttributes {
	if o == nil {
		var ret UserSessionAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UserSessionData) GetAttributesOk() (*UserSessionAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UserSessionData) SetAttributes(v UserSessionAttributes) {
	o.Attributes = v
}

func (o UserSessionData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSessionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UserSessionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSessionData := _UserSessionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserSessionData)

	if err != nil {
		return err
	}

	*o = UserSessionData(varUserSessionData)

	return err
}

type NullableUserSessionData struct {
	value *UserSessionData
	isSet bool
}

func (v NullableUserSessionData) Get() *UserSessionData {
	return v.value
}

func (v *NullableUserSessionData) Set(val *UserSessionData) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSessionData) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSessionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSessionData(val *UserSessionData) *NullableUserSessionData {
	return &NullableUserSessionData{value: val, isSet: true}
}

func (v NullableUserSessionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSessionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
