/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UploadUserMediaLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadUserMediaLinks{}

// UploadUserMediaLinks struct for UploadUserMediaLinks
type UploadUserMediaLinks struct {
	Data     UploadUserMediaLinksData `json:"data"`
	Included []UserData               `json:"included"`
}

type _UploadUserMediaLinks UploadUserMediaLinks

// NewUploadUserMediaLinks instantiates a new UploadUserMediaLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadUserMediaLinks(data UploadUserMediaLinksData, included []UserData) *UploadUserMediaLinks {
	this := UploadUserMediaLinks{}
	this.Data = data
	this.Included = included
	return &this
}

// NewUploadUserMediaLinksWithDefaults instantiates a new UploadUserMediaLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadUserMediaLinksWithDefaults() *UploadUserMediaLinks {
	this := UploadUserMediaLinks{}
	return &this
}

// GetData returns the Data field value
func (o *UploadUserMediaLinks) GetData() UploadUserMediaLinksData {
	if o == nil {
		var ret UploadUserMediaLinksData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinks) GetDataOk() (*UploadUserMediaLinksData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UploadUserMediaLinks) SetData(v UploadUserMediaLinksData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *UploadUserMediaLinks) GetIncluded() []UserData {
	if o == nil {
		var ret []UserData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinks) GetIncludedOk() ([]UserData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *UploadUserMediaLinks) SetIncluded(v []UserData) {
	o.Included = v
}

func (o UploadUserMediaLinks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadUserMediaLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *UploadUserMediaLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadUserMediaLinks := _UploadUserMediaLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadUserMediaLinks)

	if err != nil {
		return err
	}

	*o = UploadUserMediaLinks(varUploadUserMediaLinks)

	return err
}

type NullableUploadUserMediaLinks struct {
	value *UploadUserMediaLinks
	isSet bool
}

func (v NullableUploadUserMediaLinks) Get() *UploadUserMediaLinks {
	return v.value
}

func (v *NullableUploadUserMediaLinks) Set(val *UploadUserMediaLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadUserMediaLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadUserMediaLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadUserMediaLinks(val *UploadUserMediaLinks) *NullableUploadUserMediaLinks {
	return &NullableUploadUserMediaLinks{value: val, isSet: true}
}

func (v NullableUploadUserMediaLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadUserMediaLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
