/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QRTokenData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QRTokenData{}

// QRTokenData struct for QRTokenData
type QRTokenData struct {
	Type       string                `json:"type"`
	Attributes QRTokenDataAttributes `json:"attributes"`
}

type _QRTokenData QRTokenData

// NewQRTokenData instantiates a new QRTokenData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQRTokenData(type_ string, attributes QRTokenDataAttributes) *QRTokenData {
	this := QRTokenData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewQRTokenDataWithDefaults instantiates a new QRTokenData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQRTokenDataWithDefaults() *QRTokenData {
	this := QRTokenData{}
	return &this
}

// GetType returns the Type field value
func (o *QRTokenData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QRTokenData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QRTokenData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *QRTokenData) GetAttributes() QRTokenDataAttributes {
	if o == nil {
		var ret QRTokenDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *QRTokenData) GetAttributesOk() (*QRTokenDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *QRTokenData) SetAttributes(v QRTokenDataAttributes) {
	o.Attributes = v
}

func (o QRTokenData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QRTokenData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *QRTokenData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQRTokenData := _QRTokenData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQRTokenData)

	if err != nil {
		return err
	}

	*o = QRTokenData(varQRTokenData)

	return err
}

type NullableQRTokenData struct {
	value *QRTokenData
	isSet bool
}

func (v NullableQRTokenData) Get() *QRTokenData {
	return v.value
}

func (v *NullableQRTokenData) Set(val *QRTokenData) {
	v.value = val
	v.isSet = true
}

func (v NullableQRTokenData) IsSet() bool {
	return v.isSet
}

func (v *NullableQRTokenData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQRTokenData(val *QRTokenData) *NullableQRTokenData {
	return &NullableQRTokenData{value: val, isSet: true}
}

func (v NullableQRTokenData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQRTokenData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
