/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the QRTokenDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QRTokenDataAttributes{}

// QRTokenDataAttributes struct for QRTokenDataAttributes
type QRTokenDataAttributes struct {
	// Token to render as a QR code. Send it back via POST /auth-svc/v1/login/qr/confirm to complete the login. 
	QrToken uuid.UUID `json:"qr_token"`
}

type _QRTokenDataAttributes QRTokenDataAttributes

// NewQRTokenDataAttributes instantiates a new QRTokenDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQRTokenDataAttributes(qrToken uuid.UUID) *QRTokenDataAttributes {
	this := QRTokenDataAttributes{}
	this.QrToken = qrToken
	return &this
}

// NewQRTokenDataAttributesWithDefaults instantiates a new QRTokenDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQRTokenDataAttributesWithDefaults() *QRTokenDataAttributes {
	this := QRTokenDataAttributes{}
	return &this
}

// GetQrToken returns the QrToken field value
func (o *QRTokenDataAttributes) GetQrToken() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.QrToken
}

// GetQrTokenOk returns a tuple with the QrToken field value
// and a boolean to check if the value has been set.
func (o *QRTokenDataAttributes) GetQrTokenOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QrToken, true
}

// SetQrToken sets field value
func (o *QRTokenDataAttributes) SetQrToken(v uuid.UUID) {
	o.QrToken = v
}

func (o QRTokenDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QRTokenDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["qr_token"] = o.QrToken
	return toSerialize, nil
}

func (o *QRTokenDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"qr_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQRTokenDataAttributes := _QRTokenDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQRTokenDataAttributes)

	if err != nil {
		return err
	}

	*o = QRTokenDataAttributes(varQRTokenDataAttributes)

	return err
}

type NullableQRTokenDataAttributes struct {
	value *QRTokenDataAttributes
	isSet bool
}

func (v NullableQRTokenDataAttributes) Get() *QRTokenDataAttributes {
	return v.value
}

func (v *NullableQRTokenDataAttributes) Set(val *QRTokenDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableQRTokenDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableQRTokenDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQRTokenDataAttributes(val *QRTokenDataAttributes) *NullableQRTokenDataAttributes {
	return &NullableQRTokenDataAttributes{value: val, isSet: true}
}

func (v NullableQRTokenDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQRTokenDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


