/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"encoding/json"
)

// checks if the UpdateUserDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUserDataAttributes{}

// UpdateUserDataAttributes struct for UpdateUserDataAttributes
type UpdateUserDataAttributes struct {
	// pseudonym
	Pseudonym *string `json:"pseudonym,omitempty"`
	// description
	Description *string `json:"description,omitempty"`
	// avatar media key
	AvatarKey *string `json:"avatar_key,omitempty"`
}

// NewUpdateUserDataAttributes instantiates a new UpdateUserDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserDataAttributes() *UpdateUserDataAttributes {
	this := UpdateUserDataAttributes{}
	return &this
}

// NewUpdateUserDataAttributesWithDefaults instantiates a new UpdateUserDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserDataAttributesWithDefaults() *UpdateUserDataAttributes {
	this := UpdateUserDataAttributes{}
	return &this
}

// GetPseudonym returns the Pseudonym field value if set, zero value otherwise.
func (o *UpdateUserDataAttributes) GetPseudonym() string {
	if o == nil || IsNil(o.Pseudonym) {
		var ret string
		return ret
	}
	return *o.Pseudonym
}

// GetPseudonymOk returns a tuple with the Pseudonym field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserDataAttributes) GetPseudonymOk() (*string, bool) {
	if o == nil || IsNil(o.Pseudonym) {
		return nil, false
	}
	return o.Pseudonym, true
}

// HasPseudonym returns a boolean if a field has been set.
func (o *UpdateUserDataAttributes) HasPseudonym() bool {
	if o != nil && !IsNil(o.Pseudonym) {
		return true
	}

	return false
}

// SetPseudonym gets a reference to the given string and assigns it to the Pseudonym field.
func (o *UpdateUserDataAttributes) SetPseudonym(v string) {
	o.Pseudonym = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateUserDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateUserDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateUserDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetAvatarKey returns the AvatarKey field value if set, zero value otherwise.
func (o *UpdateUserDataAttributes) GetAvatarKey() string {
	if o == nil || IsNil(o.AvatarKey) {
		var ret string
		return ret
	}
	return *o.AvatarKey
}

// GetAvatarKeyOk returns a tuple with the AvatarKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserDataAttributes) GetAvatarKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarKey) {
		return nil, false
	}
	return o.AvatarKey, true
}

// HasAvatarKey returns a boolean if a field has been set.
func (o *UpdateUserDataAttributes) HasAvatarKey() bool {
	if o != nil && !IsNil(o.AvatarKey) {
		return true
	}

	return false
}

// SetAvatarKey gets a reference to the given string and assigns it to the AvatarKey field.
func (o *UpdateUserDataAttributes) SetAvatarKey(v string) {
	o.AvatarKey = &v
}

func (o UpdateUserDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUserDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pseudonym) {
		toSerialize["pseudonym"] = o.Pseudonym
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AvatarKey) {
		toSerialize["avatar_key"] = o.AvatarKey
	}
	return toSerialize, nil
}

type NullableUpdateUserDataAttributes struct {
	value *UpdateUserDataAttributes
	isSet bool
}

func (v NullableUpdateUserDataAttributes) Get() *UpdateUserDataAttributes {
	return v.value
}

func (v *NullableUpdateUserDataAttributes) Set(val *UpdateUserDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserDataAttributes(val *UpdateUserDataAttributes) *NullableUpdateUserDataAttributes {
	return &NullableUpdateUserDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateUserDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
