/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeleteUploadUserAvatar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadUserAvatar{}

// DeleteUploadUserAvatar struct for DeleteUploadUserAvatar
type DeleteUploadUserAvatar struct {
	Data DeleteUploadUserAvatarData `json:"data"`
}

type _DeleteUploadUserAvatar DeleteUploadUserAvatar

// NewDeleteUploadUserAvatar instantiates a new DeleteUploadUserAvatar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadUserAvatar(data DeleteUploadUserAvatarData) *DeleteUploadUserAvatar {
	this := DeleteUploadUserAvatar{}
	this.Data = data
	return &this
}

// NewDeleteUploadUserAvatarWithDefaults instantiates a new DeleteUploadUserAvatar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadUserAvatarWithDefaults() *DeleteUploadUserAvatar {
	this := DeleteUploadUserAvatar{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteUploadUserAvatar) GetData() DeleteUploadUserAvatarData {
	if o == nil {
		var ret DeleteUploadUserAvatarData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadUserAvatar) GetDataOk() (*DeleteUploadUserAvatarData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteUploadUserAvatar) SetData(v DeleteUploadUserAvatarData) {
	o.Data = v
}

func (o DeleteUploadUserAvatar) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadUserAvatar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteUploadUserAvatar) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadUserAvatar := _DeleteUploadUserAvatar{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadUserAvatar)

	if err != nil {
		return err
	}

	*o = DeleteUploadUserAvatar(varDeleteUploadUserAvatar)

	return err
}

type NullableDeleteUploadUserAvatar struct {
	value *DeleteUploadUserAvatar
	isSet bool
}

func (v NullableDeleteUploadUserAvatar) Get() *DeleteUploadUserAvatar {
	return v.value
}

func (v *NullableDeleteUploadUserAvatar) Set(val *DeleteUploadUserAvatar) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadUserAvatar) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadUserAvatar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadUserAvatar(val *DeleteUploadUserAvatar) *NullableDeleteUploadUserAvatar {
	return &NullableDeleteUploadUserAvatar{value: val, isSet: true}
}

func (v NullableDeleteUploadUserAvatar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadUserAvatar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
