/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the UserEmailAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserEmailAttributes{}

// UserEmailAttributes struct for UserEmailAttributes
type UserEmailAttributes struct {
	// The email address associated with the user
	Email string `json:"email"`
	// The version number of the user record
	Version int32 `json:"version"`
	// Indicates whether the email address has been verified
	Verified bool `json:"verified"`
	// The date and time when the email information was last updated
	UpdatedAt time.Time `json:"updated_at"`
	// The date and time when the email information was created
	CreatedAt time.Time `json:"created_at"`
}

type _UserEmailAttributes UserEmailAttributes

// NewUserEmailAttributes instantiates a new UserEmailAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserEmailAttributes(email string, version int32, verified bool, updatedAt time.Time, createdAt time.Time) *UserEmailAttributes {
	this := UserEmailAttributes{}
	this.Email = email
	this.Version = version
	this.Verified = verified
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewUserEmailAttributesWithDefaults instantiates a new UserEmailAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserEmailAttributesWithDefaults() *UserEmailAttributes {
	this := UserEmailAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *UserEmailAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserEmailAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserEmailAttributes) SetEmail(v string) {
	o.Email = v
}

// GetVersion returns the Version field value
func (o *UserEmailAttributes) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *UserEmailAttributes) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *UserEmailAttributes) SetVersion(v int32) {
	o.Version = v
}

// GetVerified returns the Verified field value
func (o *UserEmailAttributes) GetVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value
// and a boolean to check if the value has been set.
func (o *UserEmailAttributes) GetVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verified, true
}

// SetVerified sets field value
func (o *UserEmailAttributes) SetVerified(v bool) {
	o.Verified = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserEmailAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserEmailAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserEmailAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserEmailAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserEmailAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserEmailAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o UserEmailAttributes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserEmailAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["version"] = o.Version
	toSerialize["verified"] = o.Verified
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *UserEmailAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"version",
		"verified",
		"updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserEmailAttributes := _UserEmailAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserEmailAttributes)

	if err != nil {
		return err
	}

	*o = UserEmailAttributes(varUserEmailAttributes)

	return err
}

type NullableUserEmailAttributes struct {
	value *UserEmailAttributes
	isSet bool
}

func (v NullableUserEmailAttributes) Get() *UserEmailAttributes {
	return v.value
}

func (v *NullableUserEmailAttributes) Set(val *UserEmailAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUserEmailAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUserEmailAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserEmailAttributes(val *UserEmailAttributes) *NullableUserEmailAttributes {
	return &NullableUserEmailAttributes{value: val, isSet: true}
}

func (v NullableUserEmailAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserEmailAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
