/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"encoding/json"
)

// checks if the UploadUserMediaLinksDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadUserMediaLinksDataRelationships{}

// UploadUserMediaLinksDataRelationships struct for UploadUserMediaLinksDataRelationships
type UploadUserMediaLinksDataRelationships struct {
	User *UploadUserMediaLinksDataRelationshipsUser `json:"user,omitempty"`
}

// NewUploadUserMediaLinksDataRelationships instantiates a new UploadUserMediaLinksDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadUserMediaLinksDataRelationships() *UploadUserMediaLinksDataRelationships {
	this := UploadUserMediaLinksDataRelationships{}
	return &this
}

// NewUploadUserMediaLinksDataRelationshipsWithDefaults instantiates a new UploadUserMediaLinksDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadUserMediaLinksDataRelationshipsWithDefaults() *UploadUserMediaLinksDataRelationships {
	this := UploadUserMediaLinksDataRelationships{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *UploadUserMediaLinksDataRelationships) GetUser() UploadUserMediaLinksDataRelationshipsUser {
	if o == nil || IsNil(o.User) {
		var ret UploadUserMediaLinksDataRelationshipsUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinksDataRelationships) GetUserOk() (*UploadUserMediaLinksDataRelationshipsUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *UploadUserMediaLinksDataRelationships) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given UploadUserMediaLinksDataRelationshipsUser and assigns it to the User field.
func (o *UploadUserMediaLinksDataRelationships) SetUser(v UploadUserMediaLinksDataRelationshipsUser) {
	o.User = &v
}

func (o UploadUserMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadUserMediaLinksDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableUploadUserMediaLinksDataRelationships struct {
	value *UploadUserMediaLinksDataRelationships
	isSet bool
}

func (v NullableUploadUserMediaLinksDataRelationships) Get() *UploadUserMediaLinksDataRelationships {
	return v.value
}

func (v *NullableUploadUserMediaLinksDataRelationships) Set(val *UploadUserMediaLinksDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadUserMediaLinksDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadUserMediaLinksDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadUserMediaLinksDataRelationships(val *UploadUserMediaLinksDataRelationships) *NullableUploadUserMediaLinksDataRelationships {
	return &NullableUploadUserMediaLinksDataRelationships{value: val, isSet: true}
}

func (v NullableUploadUserMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadUserMediaLinksDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
