/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/google/uuid"
)

// checks if the UploadUserMediaLinksDataRelationshipsUserData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadUserMediaLinksDataRelationshipsUserData{}

// UploadUserMediaLinksDataRelationshipsUserData struct for UploadUserMediaLinksDataRelationshipsUserData
type UploadUserMediaLinksDataRelationshipsUserData struct {
	// User id
	Id   uuid.UUID `json:"id"`
	Type string    `json:"type"`
}

type _UploadUserMediaLinksDataRelationshipsUserData UploadUserMediaLinksDataRelationshipsUserData

// NewUploadUserMediaLinksDataRelationshipsUserData instantiates a new UploadUserMediaLinksDataRelationshipsUserData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadUserMediaLinksDataRelationshipsUserData(id uuid.UUID, type_ string) *UploadUserMediaLinksDataRelationshipsUserData {
	this := UploadUserMediaLinksDataRelationshipsUserData{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewUploadUserMediaLinksDataRelationshipsUserDataWithDefaults instantiates a new UploadUserMediaLinksDataRelationshipsUserData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadUserMediaLinksDataRelationshipsUserDataWithDefaults() *UploadUserMediaLinksDataRelationshipsUserData {
	this := UploadUserMediaLinksDataRelationshipsUserData{}
	return &this
}

// GetId returns the Id field value
func (o *UploadUserMediaLinksDataRelationshipsUserData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinksDataRelationshipsUserData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UploadUserMediaLinksDataRelationshipsUserData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UploadUserMediaLinksDataRelationshipsUserData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UploadUserMediaLinksDataRelationshipsUserData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UploadUserMediaLinksDataRelationshipsUserData) SetType(v string) {
	o.Type = v
}

func (o UploadUserMediaLinksDataRelationshipsUserData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadUserMediaLinksDataRelationshipsUserData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *UploadUserMediaLinksDataRelationshipsUserData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadUserMediaLinksDataRelationshipsUserData := _UploadUserMediaLinksDataRelationshipsUserData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadUserMediaLinksDataRelationshipsUserData)

	if err != nil {
		return err
	}

	*o = UploadUserMediaLinksDataRelationshipsUserData(varUploadUserMediaLinksDataRelationshipsUserData)

	return err
}

type NullableUploadUserMediaLinksDataRelationshipsUserData struct {
	value *UploadUserMediaLinksDataRelationshipsUserData
	isSet bool
}

func (v NullableUploadUserMediaLinksDataRelationshipsUserData) Get() *UploadUserMediaLinksDataRelationshipsUserData {
	return v.value
}

func (v *NullableUploadUserMediaLinksDataRelationshipsUserData) Set(val *UploadUserMediaLinksDataRelationshipsUserData) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadUserMediaLinksDataRelationshipsUserData) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadUserMediaLinksDataRelationshipsUserData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadUserMediaLinksDataRelationshipsUserData(val *UploadUserMediaLinksDataRelationshipsUserData) *NullableUploadUserMediaLinksDataRelationshipsUserData {
	return &NullableUploadUserMediaLinksDataRelationshipsUserData{value: val, isSet: true}
}

func (v NullableUploadUserMediaLinksDataRelationshipsUserData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadUserMediaLinksDataRelationshipsUserData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
