/*
netbill auth-svc API

API documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QRToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QRToken{}

// QRToken struct for QRToken
type QRToken struct {
	Data QRTokenData `json:"data"`
}

type _QRToken QRToken

// NewQRToken instantiates a new QRToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQRToken(data QRTokenData) *QRToken {
	this := QRToken{}
	this.Data = data
	return &this
}

// NewQRTokenWithDefaults instantiates a new QRToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQRTokenWithDefaults() *QRToken {
	this := QRToken{}
	return &this
}

// GetData returns the Data field value
func (o *QRToken) GetData() QRTokenData {
	if o == nil {
		var ret QRTokenData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *QRToken) GetDataOk() (*QRTokenData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *QRToken) SetData(v QRTokenData) {
	o.Data = v
}

func (o QRToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QRToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *QRToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQRToken := _QRToken{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQRToken)

	if err != nil {
		return err
	}

	*o = QRToken(varQRToken)

	return err
}

type NullableQRToken struct {
	value *QRToken
	isSet bool
}

func (v NullableQRToken) Get() *QRToken {
	return v.value
}

func (v *NullableQRToken) Set(val *QRToken) {
	v.value = val
	v.isSet = true
}

func (v NullableQRToken) IsSet() bool {
	return v.isSet
}

func (v *NullableQRToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQRToken(val *QRToken) *NullableQRToken {
	return &NullableQRToken{value: val, isSet: true}
}

func (v NullableQRToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQRToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


