service:
  name: "auth-svc"

log:
  level: "debug"   # debug | info | warn | error
  format: "text"   # text | json

database:
  sql:
    url: "${DATABASE_SQL_URL}"  # env:

rest:
  port: 8001
  timeouts:
    read: 15s
    read_header: 15s
    write: 15s
    idle: 60s

auth:
  tokens:
    issuer: "auth-svc"
    account_access:
      secret_key: "${AUTH_TOKENS_ACCOUNT_ACCESS_SECRET_KEY}"
      ttl: 720h
    account_refresh:
      secret_key: "${AUTH_TOKENS_ACCOUNT_REFRESH_SECRET_KEY}"
      hash_key: "${AUTH_TOKENS_ACCOUNT_REFRESH_HASH_KEY}"
      ttl: 720h

  oauth:
    google:
      client_id: "${AUTH_OAUTH_GOOGLE_CLIENT_ID}"
      client_secret: "${AUTH_OAUTH_GOOGLE_CLIENT_SECRET}"
      redirect_url: "${AUTH_OAUTH_GOOGLE_REDIRECT_URL}"

kafka:
  brokers:
    - "${KAFKA_BROKERS}"

  identity: "auth-svc"  # consumer group id и client id

  produce:
    topics:
      accounts_v1:
        required_acks: "all"     # all | one | none
        compression: "snappy"    # snappy | gzip | lz4 | zstd | none
        balancer: "hash"         # least_bytes | round_robin | hash
        batch_size: 100
        batch_timeout: 10ms
        write_timeout: 5s
        read_timeout: 5s
        dial_timeout: 5s
        idle_timeout: 30s

  consume:
    backoff:
      min: 100ms
      max: 1s

    topics:
      organizations_v1:
        instances: 4
        min_bytes: 1
        max_bytes: 10e6
        max_wait: 1s
        queue_capacity: 10

      organization_members_v1:
        instances: 4
        min_bytes: 1
        max_bytes: 10e6
        max_wait: 1s
        queue_capacity: 10
