service:
  name: "auth-svc"

log:
  level: "debug"   # debug | info | warn | error
  format: "text"   # text | json

database:
  sql:
    url: "${DATABASE_SQL_URL}"  # env:

rest:
  port: 8001
  timeouts:
    read: 15s
    read_header: 15s
    write: 15s
    idle: 60s

auth:
  tokens:
    issuer: "auth-svc"
    account_access:
      secret_key: "${AUTH_TOKENS_ACCOUNT_ACCESS_SECRET_KEY}"
      ttl: 720h
    account_refresh:
      secret_key: "${AUTH_TOKENS_ACCOUNT_REFRESH_SECRET_KEY}"
      hash_key: "${AUTH_TOKENS_ACCOUNT_REFRESH_HASH_KEY}"
      ttl: 720h

  oauth:
    google:
      client_id: "${AUTH_OAUTH_GOOGLE_CLIENT_ID}"
      client_secret: "${AUTH_OAUTH_GOOGLE_CLIENT_SECRET}"
      redirect_url: "${AUTH_OAUTH_GOOGLE_REDIRECT_URL}"

redis:
  addr: "${REDIS_ADDR}"
  password: "${REDIS_PASSWORD}"
  db: 0

  ttl:
    account: 5m
    email: 5m
    password: 5m
    session: 5m

kafka:
  brokers:
    - "${KAFKA_BROKERS}"

  identity: "auth-svc"  # consumer group id и client id