/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the AccessTokenDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessTokenDataAttributes{}

// AccessTokenDataAttributes struct for AccessTokenDataAttributes
type AccessTokenDataAttributes struct {
	// The access token to generate a new access token.
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// NewAccessTokenDataAttributes instantiates a new AccessTokenDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessTokenDataAttributes() *AccessTokenDataAttributes {
	this := AccessTokenDataAttributes{}
	return &this
}

// NewAccessTokenDataAttributesWithDefaults instantiates a new AccessTokenDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessTokenDataAttributesWithDefaults() *AccessTokenDataAttributes {
	this := AccessTokenDataAttributes{}
	return &this
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *AccessTokenDataAttributes) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokenDataAttributes) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *AccessTokenDataAttributes) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *AccessTokenDataAttributes) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

func (o AccessTokenDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessTokenDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefreshToken) {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	return toSerialize, nil
}

type NullableAccessTokenDataAttributes struct {
	value *AccessTokenDataAttributes
	isSet bool
}

func (v NullableAccessTokenDataAttributes) Get() *AccessTokenDataAttributes {
	return v.value
}

func (v *NullableAccessTokenDataAttributes) Set(val *AccessTokenDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessTokenDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessTokenDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessTokenDataAttributes(val *AccessTokenDataAttributes) *NullableAccessTokenDataAttributes {
	return &NullableAccessTokenDataAttributes{value: val, isSet: true}
}

func (v NullableAccessTokenDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessTokenDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


