/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginByEmailDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginByEmailDataAttributes{}

// LoginByEmailDataAttributes struct for LoginByEmailDataAttributes
type LoginByEmailDataAttributes struct {
	// The account's email address.
	Email string `json:"email"`
	// The account's password.
	Password string `json:"password"`
}

type _LoginByEmailDataAttributes LoginByEmailDataAttributes

// NewLoginByEmailDataAttributes instantiates a new LoginByEmailDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginByEmailDataAttributes(email string, password string) *LoginByEmailDataAttributes {
	this := LoginByEmailDataAttributes{}
	this.Email = email
	this.Password = password
	return &this
}

// NewLoginByEmailDataAttributesWithDefaults instantiates a new LoginByEmailDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginByEmailDataAttributesWithDefaults() *LoginByEmailDataAttributes {
	this := LoginByEmailDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginByEmailDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginByEmailDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginByEmailDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *LoginByEmailDataAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginByEmailDataAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginByEmailDataAttributes) SetPassword(v string) {
	o.Password = v
}

func (o LoginByEmailDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginByEmailDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *LoginByEmailDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginByEmailDataAttributes := _LoginByEmailDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginByEmailDataAttributes)

	if err != nil {
		return err
	}

	*o = LoginByEmailDataAttributes(varLoginByEmailDataAttributes)

	return err
}

type NullableLoginByEmailDataAttributes struct {
	value *LoginByEmailDataAttributes
	isSet bool
}

func (v NullableLoginByEmailDataAttributes) Get() *LoginByEmailDataAttributes {
	return v.value
}

func (v *NullableLoginByEmailDataAttributes) Set(val *LoginByEmailDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginByEmailDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginByEmailDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginByEmailDataAttributes(val *LoginByEmailDataAttributes) *NullableLoginByEmailDataAttributes {
	return &NullableLoginByEmailDataAttributes{value: val, isSet: true}
}

func (v NullableLoginByEmailDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginByEmailDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


