/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccountSessionsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountSessionsCollection{}

// AccountSessionsCollection struct for AccountSessionsCollection
type AccountSessionsCollection struct {
	Data []AccountSessionData `json:"data"`
	Links PaginationData `json:"links"`
}

type _AccountSessionsCollection AccountSessionsCollection

// NewAccountSessionsCollection instantiates a new AccountSessionsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountSessionsCollection(data []AccountSessionData, links PaginationData) *AccountSessionsCollection {
	this := AccountSessionsCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewAccountSessionsCollectionWithDefaults instantiates a new AccountSessionsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountSessionsCollectionWithDefaults() *AccountSessionsCollection {
	this := AccountSessionsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *AccountSessionsCollection) GetData() []AccountSessionData {
	if o == nil {
		var ret []AccountSessionData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AccountSessionsCollection) GetDataOk() ([]AccountSessionData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AccountSessionsCollection) SetData(v []AccountSessionData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *AccountSessionsCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AccountSessionsCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AccountSessionsCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o AccountSessionsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountSessionsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *AccountSessionsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountSessionsCollection := _AccountSessionsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountSessionsCollection)

	if err != nil {
		return err
	}

	*o = AccountSessionsCollection(varAccountSessionsCollection)

	return err
}

type NullableAccountSessionsCollection struct {
	value *AccountSessionsCollection
	isSet bool
}

func (v NullableAccountSessionsCollection) Get() *AccountSessionsCollection {
	return v.value
}

func (v *NullableAccountSessionsCollection) Set(val *AccountSessionsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountSessionsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountSessionsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountSessionsCollection(val *AccountSessionsCollection) *NullableAccountSessionsCollection {
	return &NullableAccountSessionsCollection{value: val, isSet: true}
}

func (v NullableAccountSessionsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountSessionsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


