/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokensPair type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokensPair{}

// TokensPair struct for TokensPair
type TokensPair struct {
	Data TokensPairData `json:"data"`
}

type _TokensPair TokensPair

// NewTokensPair instantiates a new TokensPair object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokensPair(data TokensPairData) *TokensPair {
	this := TokensPair{}
	this.Data = data
	return &this
}

// NewTokensPairWithDefaults instantiates a new TokensPair object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokensPairWithDefaults() *TokensPair {
	this := TokensPair{}
	return &this
}

// GetData returns the Data field value
func (o *TokensPair) GetData() TokensPairData {
	if o == nil {
		var ret TokensPairData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TokensPair) GetDataOk() (*TokensPairData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *TokensPair) SetData(v TokensPairData) {
	o.Data = v
}

func (o TokensPair) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokensPair) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *TokensPair) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokensPair := _TokensPair{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokensPair)

	if err != nil {
		return err
	}

	*o = TokensPair(varTokensPair)

	return err
}

type NullableTokensPair struct {
	value *TokensPair
	isSet bool
}

func (v NullableTokensPair) Get() *TokensPair {
	return v.value
}

func (v *NullableTokensPair) Set(val *TokensPair) {
	v.value = val
	v.isSet = true
}

func (v NullableTokensPair) IsSet() bool {
	return v.isSet
}

func (v *NullableTokensPair) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokensPair(val *TokensPair) *NullableTokensPair {
	return &NullableTokensPair{value: val, isSet: true}
}

func (v NullableTokensPair) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokensPair) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


