/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateUsername type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateUsername{}

// UpdateUsername struct for UpdateUsername
type UpdateUsername struct {
	Data UpdateUsernameData `json:"data"`
}

type _UpdateUsername UpdateUsername

// NewUpdateUsername instantiates a new UpdateUsername object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUsername(data UpdateUsernameData) *UpdateUsername {
	this := UpdateUsername{}
	this.Data = data
	return &this
}

// NewUpdateUsernameWithDefaults instantiates a new UpdateUsername object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUsernameWithDefaults() *UpdateUsername {
	this := UpdateUsername{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateUsername) GetData() UpdateUsernameData {
	if o == nil {
		var ret UpdateUsernameData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateUsername) GetDataOk() (*UpdateUsernameData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateUsername) SetData(v UpdateUsernameData) {
	o.Data = v
}

func (o UpdateUsername) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateUsername) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateUsername) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateUsername := _UpdateUsername{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateUsername)

	if err != nil {
		return err
	}

	*o = UpdateUsername(varUpdateUsername)

	return err
}

type NullableUpdateUsername struct {
	value *UpdateUsername
	isSet bool
}

func (v NullableUpdateUsername) Get() *UpdateUsername {
	return v.value
}

func (v *NullableUpdateUsername) Set(val *UpdateUsername) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUsername) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUsername) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUsername(val *UpdateUsername) *NullableUpdateUsername {
	return &NullableUpdateUsername{value: val, isSet: true}
}

func (v NullableUpdateUsername) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUsername) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


