/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationAdmin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationAdmin{}

// RegistrationAdmin struct for RegistrationAdmin
type RegistrationAdmin struct {
	Data RegistrationAdminData `json:"data"`
}

type _RegistrationAdmin RegistrationAdmin

// NewRegistrationAdmin instantiates a new RegistrationAdmin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationAdmin(data RegistrationAdminData) *RegistrationAdmin {
	this := RegistrationAdmin{}
	this.Data = data
	return &this
}

// NewRegistrationAdminWithDefaults instantiates a new RegistrationAdmin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationAdminWithDefaults() *RegistrationAdmin {
	this := RegistrationAdmin{}
	return &this
}

// GetData returns the Data field value
func (o *RegistrationAdmin) GetData() RegistrationAdminData {
	if o == nil {
		var ret RegistrationAdminData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RegistrationAdmin) GetDataOk() (*RegistrationAdminData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RegistrationAdmin) SetData(v RegistrationAdminData) {
	o.Data = v
}

func (o RegistrationAdmin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationAdmin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RegistrationAdmin) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationAdmin := _RegistrationAdmin{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationAdmin)

	if err != nil {
		return err
	}

	*o = RegistrationAdmin(varRegistrationAdmin)

	return err
}

type NullableRegistrationAdmin struct {
	value *RegistrationAdmin
	isSet bool
}

func (v NullableRegistrationAdmin) Get() *RegistrationAdmin {
	return v.value
}

func (v *NullableRegistrationAdmin) Set(val *RegistrationAdmin) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationAdmin) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationAdmin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationAdmin(val *RegistrationAdmin) *NullableRegistrationAdmin {
	return &NullableRegistrationAdmin{value: val, isSet: true}
}

func (v NullableRegistrationAdmin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationAdmin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


