/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePasswordData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePasswordData{}

// UpdatePasswordData struct for UpdatePasswordData
type UpdatePasswordData struct {
	Type string `json:"type"`
	Attributes UpdatePasswordDataAttributes `json:"attributes"`
}

type _UpdatePasswordData UpdatePasswordData

// NewUpdatePasswordData instantiates a new UpdatePasswordData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePasswordData(type_ string, attributes UpdatePasswordDataAttributes) *UpdatePasswordData {
	this := UpdatePasswordData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdatePasswordDataWithDefaults instantiates a new UpdatePasswordData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePasswordDataWithDefaults() *UpdatePasswordData {
	this := UpdatePasswordData{}
	return &this
}

// GetType returns the Type field value
func (o *UpdatePasswordData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdatePasswordData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdatePasswordData) GetAttributes() UpdatePasswordDataAttributes {
	if o == nil {
		var ret UpdatePasswordDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordData) GetAttributesOk() (*UpdatePasswordDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdatePasswordData) SetAttributes(v UpdatePasswordDataAttributes) {
	o.Attributes = v
}

func (o UpdatePasswordData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePasswordData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdatePasswordData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePasswordData := _UpdatePasswordData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePasswordData)

	if err != nil {
		return err
	}

	*o = UpdatePasswordData(varUpdatePasswordData)

	return err
}

type NullableUpdatePasswordData struct {
	value *UpdatePasswordData
	isSet bool
}

func (v NullableUpdatePasswordData) Get() *UpdatePasswordData {
	return v.value
}

func (v *NullableUpdatePasswordData) Set(val *UpdatePasswordData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePasswordData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePasswordData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePasswordData(val *UpdatePasswordData) *NullableUpdatePasswordData {
	return &NullableUpdatePasswordData{value: val, isSet: true}
}

func (v NullableUpdatePasswordData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePasswordData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


