/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the AccountEmail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountEmail{}

// AccountEmail struct for AccountEmail
type AccountEmail struct {
	// account ID
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes AccountEmailAttributes `json:"attributes"`
}

type _AccountEmail AccountEmail

// NewAccountEmail instantiates a new AccountEmail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountEmail(id uuid.UUID, type_ string, attributes AccountEmailAttributes) *AccountEmail {
	this := AccountEmail{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAccountEmailWithDefaults instantiates a new AccountEmail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountEmailWithDefaults() *AccountEmail {
	this := AccountEmail{}
	return &this
}

// GetId returns the Id field value
func (o *AccountEmail) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccountEmail) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccountEmail) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AccountEmail) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AccountEmail) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AccountEmail) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AccountEmail) GetAttributes() AccountEmailAttributes {
	if o == nil {
		var ret AccountEmailAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AccountEmail) GetAttributesOk() (*AccountEmailAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AccountEmail) SetAttributes(v AccountEmailAttributes) {
	o.Attributes = v
}

func (o AccountEmail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountEmail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AccountEmail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountEmail := _AccountEmail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountEmail)

	if err != nil {
		return err
	}

	*o = AccountEmail(varAccountEmail)

	return err
}

type NullableAccountEmail struct {
	value *AccountEmail
	isSet bool
}

func (v NullableAccountEmail) Get() *AccountEmail {
	return v.value
}

func (v *NullableAccountEmail) Set(val *AccountEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountEmail(val *AccountEmail) *NullableAccountEmail {
	return &NullableAccountEmail{value: val, isSet: true}
}

func (v NullableAccountEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


