/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePasswordDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePasswordDataAttributes{}

// UpdatePasswordDataAttributes struct for UpdatePasswordDataAttributes
type UpdatePasswordDataAttributes struct {
	// The account's current password.
	OldPassword string `json:"old_password"`
	// The account's password.
	NewPassword string `json:"new_password"`
}

type _UpdatePasswordDataAttributes UpdatePasswordDataAttributes

// NewUpdatePasswordDataAttributes instantiates a new UpdatePasswordDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePasswordDataAttributes(oldPassword string, newPassword string) *UpdatePasswordDataAttributes {
	this := UpdatePasswordDataAttributes{}
	this.OldPassword = oldPassword
	this.NewPassword = newPassword
	return &this
}

// NewUpdatePasswordDataAttributesWithDefaults instantiates a new UpdatePasswordDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePasswordDataAttributesWithDefaults() *UpdatePasswordDataAttributes {
	this := UpdatePasswordDataAttributes{}
	return &this
}

// GetOldPassword returns the OldPassword field value
func (o *UpdatePasswordDataAttributes) GetOldPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OldPassword
}

// GetOldPasswordOk returns a tuple with the OldPassword field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordDataAttributes) GetOldPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldPassword, true
}

// SetOldPassword sets field value
func (o *UpdatePasswordDataAttributes) SetOldPassword(v string) {
	o.OldPassword = v
}

// GetNewPassword returns the NewPassword field value
func (o *UpdatePasswordDataAttributes) GetNewPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewPassword
}

// GetNewPasswordOk returns a tuple with the NewPassword field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordDataAttributes) GetNewPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewPassword, true
}

// SetNewPassword sets field value
func (o *UpdatePasswordDataAttributes) SetNewPassword(v string) {
	o.NewPassword = v
}

func (o UpdatePasswordDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePasswordDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["old_password"] = o.OldPassword
	toSerialize["new_password"] = o.NewPassword
	return toSerialize, nil
}

func (o *UpdatePasswordDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"old_password",
		"new_password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePasswordDataAttributes := _UpdatePasswordDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePasswordDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdatePasswordDataAttributes(varUpdatePasswordDataAttributes)

	return err
}

type NullableUpdatePasswordDataAttributes struct {
	value *UpdatePasswordDataAttributes
	isSet bool
}

func (v NullableUpdatePasswordDataAttributes) Get() *UpdatePasswordDataAttributes {
	return v.value
}

func (v *NullableUpdatePasswordDataAttributes) Set(val *UpdatePasswordDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePasswordDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePasswordDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePasswordDataAttributes(val *UpdatePasswordDataAttributes) *NullableUpdatePasswordDataAttributes {
	return &NullableUpdatePasswordDataAttributes{value: val, isSet: true}
}

func (v NullableUpdatePasswordDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePasswordDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


