/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginByEmail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginByEmail{}

// LoginByEmail struct for LoginByEmail
type LoginByEmail struct {
	Data LoginByEmailData `json:"data"`
}

type _LoginByEmail LoginByEmail

// NewLoginByEmail instantiates a new LoginByEmail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginByEmail(data LoginByEmailData) *LoginByEmail {
	this := LoginByEmail{}
	this.Data = data
	return &this
}

// NewLoginByEmailWithDefaults instantiates a new LoginByEmail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginByEmailWithDefaults() *LoginByEmail {
	this := LoginByEmail{}
	return &this
}

// GetData returns the Data field value
func (o *LoginByEmail) GetData() LoginByEmailData {
	if o == nil {
		var ret LoginByEmailData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *LoginByEmail) GetDataOk() (*LoginByEmailData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *LoginByEmail) SetData(v LoginByEmailData) {
	o.Data = v
}

func (o LoginByEmail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginByEmail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *LoginByEmail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginByEmail := _LoginByEmail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginByEmail)

	if err != nil {
		return err
	}

	*o = LoginByEmail(varLoginByEmail)

	return err
}

type NullableLoginByEmail struct {
	value *LoginByEmail
	isSet bool
}

func (v NullableLoginByEmail) Get() *LoginByEmail {
	return v.value
}

func (v *NullableLoginByEmail) Set(val *LoginByEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginByEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginByEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginByEmail(val *LoginByEmail) *NullableLoginByEmail {
	return &NullableLoginByEmail{value: val, isSet: true}
}

func (v NullableLoginByEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginByEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


