// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import mock "github.com/stretchr/testify/mock"

// mockUsernameValidator is an autogenerated mock type for the usernameValidator type
type mockUsernameValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: username
func (_m *mockUsernameValidator) Validate(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockUsernameValidator creates a new instance of mockUsernameValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUsernameValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUsernameValidator {
	mock := &mockUsernameValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
