// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// mockSessionsCache is an autogenerated mock type for the sessionsCache type
type mockSessionsCache struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, sessionID
func (_m *mockSessionsCache) Delete(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockSessionsCache creates a new instance of mockSessionsCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionsCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionsCache {
	mock := &mockSessionsCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
