// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// mockMessenger is an autogenerated mock type for the messenger type
type mockMessenger struct {
	mock.Mock
}

// WriteUserCreated provides a mock function with given fields: ctx, user, email
func (_m *mockMessenger) WriteUserCreated(ctx context.Context, user models.User, email models.UserEmail) error {
	ret := _m.Called(ctx, user, email)

	if len(ret) == 0 {
		panic("no return value specified for WriteUserCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User, models.UserEmail) error); ok {
		r0 = rf(ctx, user, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteUserDeleted provides a mock function with given fields: ctx, user, email
func (_m *mockMessenger) WriteUserDeleted(ctx context.Context, user models.User, email models.UserEmail) error {
	ret := _m.Called(ctx, user, email)

	if len(ret) == 0 {
		panic("no return value specified for WriteUserDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User, models.UserEmail) error); ok {
		r0 = rf(ctx, user, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteUserUpdated provides a mock function with given fields: ctx, user
func (_m *mockMessenger) WriteUserUpdated(ctx context.Context, user models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for WriteUserUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockMessenger creates a new instance of mockMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMessenger {
	mock := &mockMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
