// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import mock "github.com/stretchr/testify/mock"

// mockUsernameGenerator is an autogenerated mock type for the usernameGenerator type
type mockUsernameGenerator struct {
	mock.Mock
}

// Generate provides a mock function with no fields
func (_m *mockUsernameGenerator) Generate() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Validate provides a mock function with given fields: username
func (_m *mockUsernameGenerator) Validate(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockUsernameGenerator creates a new instance of mockUsernameGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUsernameGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUsernameGenerator {
	mock := &mockUsernameGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
