// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockPasswordRepo is an autogenerated mock type for the passwordRepo type
type mockPasswordRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *mockPasswordRepo) Create(ctx context.Context, params models.UserPassword) (models.UserPassword, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.UserPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserPassword) (models.UserPassword, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserPassword) models.UserPassword); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.UserPassword)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserPassword) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *mockPasswordRepo) GetByID(ctx context.Context, userID uuid.UUID) (models.UserPassword, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.UserPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.UserPassword, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.UserPassword); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.UserPassword)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePassword provides a mock function with given fields: ctx, userID, passwordHash
func (_m *mockPasswordRepo) UpdatePassword(ctx context.Context, userID uuid.UUID, passwordHash string) (models.UserPassword, error) {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 models.UserPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (models.UserPassword, error)); ok {
		return rf(ctx, userID, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) models.UserPassword); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Get(0).(models.UserPassword)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockPasswordRepo creates a new instance of mockPasswordRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPasswordRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPasswordRepo {
	mock := &mockPasswordRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
