// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockEmailRepo is an autogenerated mock type for the emailRepo type
type mockEmailRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *mockEmailRepo) Create(ctx context.Context, params models.UserEmail) (models.UserEmail, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.UserEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserEmail) (models.UserEmail, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserEmail) models.UserEmail); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(models.UserEmail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserEmail) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, userID, opts
func (_m *mockEmailRepo) GetByID(ctx context.Context, userID uuid.UUID, opts ...GetUserOption) (models.UserEmail, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, userID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.UserEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...GetUserOption) (models.UserEmail, error)); ok {
		return rf(ctx, userID, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...GetUserOption) models.UserEmail); ok {
		r0 = rf(ctx, userID, opts...)
	} else {
		r0 = ret.Get(0).(models.UserEmail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...GetUserOption) error); ok {
		r1 = rf(ctx, userID, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockEmailRepo creates a new instance of mockEmailRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEmailRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEmailRepo {
	mock := &mockEmailRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
