// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import mock "github.com/stretchr/testify/mock"

// mockPasswordManager is an autogenerated mock type for the passwordManager type
type mockPasswordManager struct {
	mock.Mock
}

// CheckMatch provides a mock function with given fields: password, hash
func (_m *mockPasswordManager) CheckMatch(password string, hash string) error {
	ret := _m.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for CheckMatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateHash provides a mock function with given fields: password
func (_m *mockPasswordManager) GenerateHash(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for GenerateHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockPasswordManager creates a new instance of mockPasswordManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPasswordManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPasswordManager {
	mock := &mockPasswordManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
