// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockMedia is an autogenerated mock type for the media type
type mockMedia struct {
	mock.Mock
}

// CreateUserAvatarUploadMediaLinks provides a mock function with given fields: ctx, userID
func (_m *mockMedia) CreateUserAvatarUploadMediaLinks(ctx context.Context, userID uuid.UUID) (models.UploadMediaLink, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserAvatarUploadMediaLinks")
	}

	var r0 models.UploadMediaLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.UploadMediaLink, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.UploadMediaLink); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.UploadMediaLink)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUploadUserAvatar provides a mock function with given fields: ctx, userID, key
func (_m *mockMedia) DeleteUploadUserAvatar(ctx context.Context, userID uuid.UUID, key string) error {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUploadUserAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserAvatar provides a mock function with given fields: ctx, userID, key
func (_m *mockMedia) DeleteUserAvatar(ctx context.Context, userID uuid.UUID, key string) error {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserAvatar provides a mock function with given fields: ctx, userID, key
func (_m *mockMedia) UpdateUserAvatar(ctx context.Context, userID uuid.UUID, key string) (string, error) {
	ret := _m.Called(ctx, userID, key)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserAvatar")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (string, error)); ok {
		return rf(ctx, userID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) string); ok {
		r0 = rf(ctx, userID, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockMedia creates a new instance of mockMedia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMedia(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMedia {
	mock := &mockMedia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
