/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginByUsernameData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginByUsernameData{}

// LoginByUsernameData struct for LoginByUsernameData
type LoginByUsernameData struct {
	Type string `json:"type"`
	Attributes LoginByUsernameDataAttributes `json:"attributes"`
}

type _LoginByUsernameData LoginByUsernameData

// NewLoginByUsernameData instantiates a new LoginByUsernameData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginByUsernameData(type_ string, attributes LoginByUsernameDataAttributes) *LoginByUsernameData {
	this := LoginByUsernameData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewLoginByUsernameDataWithDefaults instantiates a new LoginByUsernameData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginByUsernameDataWithDefaults() *LoginByUsernameData {
	this := LoginByUsernameData{}
	return &this
}

// GetType returns the Type field value
func (o *LoginByUsernameData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *LoginByUsernameData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *LoginByUsernameData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *LoginByUsernameData) GetAttributes() LoginByUsernameDataAttributes {
	if o == nil {
		var ret LoginByUsernameDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *LoginByUsernameData) GetAttributesOk() (*LoginByUsernameDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *LoginByUsernameData) SetAttributes(v LoginByUsernameDataAttributes) {
	o.Attributes = v
}

func (o LoginByUsernameData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginByUsernameData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *LoginByUsernameData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginByUsernameData := _LoginByUsernameData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginByUsernameData)

	if err != nil {
		return err
	}

	*o = LoginByUsernameData(varLoginByUsernameData)

	return err
}

type NullableLoginByUsernameData struct {
	value *LoginByUsernameData
	isSet bool
}

func (v NullableLoginByUsernameData) Get() *LoginByUsernameData {
	return v.value
}

func (v *NullableLoginByUsernameData) Set(val *LoginByUsernameData) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginByUsernameData) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginByUsernameData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginByUsernameData(val *LoginByUsernameData) *NullableLoginByUsernameData {
	return &NullableLoginByUsernameData{value: val, isSet: true}
}

func (v NullableLoginByUsernameData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginByUsernameData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


