/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
	"bytes"
	"fmt"
)

// checks if the AccountSessionAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountSessionAttributes{}

// AccountSessionAttributes struct for AccountSessionAttributes
type AccountSessionAttributes struct {
	// account id
	AccountId uuid.UUID `json:"account_id"`
	// session creation date
	CreatedAt time.Time `json:"created_at"`
	// last used date
	LastUsed time.Time `json:"last_used"`
}

type _AccountSessionAttributes AccountSessionAttributes

// NewAccountSessionAttributes instantiates a new AccountSessionAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountSessionAttributes(accountId uuid.UUID, createdAt time.Time, lastUsed time.Time) *AccountSessionAttributes {
	this := AccountSessionAttributes{}
	this.AccountId = accountId
	this.CreatedAt = createdAt
	this.LastUsed = lastUsed
	return &this
}

// NewAccountSessionAttributesWithDefaults instantiates a new AccountSessionAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountSessionAttributesWithDefaults() *AccountSessionAttributes {
	this := AccountSessionAttributes{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AccountSessionAttributes) GetAccountId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AccountSessionAttributes) GetAccountIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AccountSessionAttributes) SetAccountId(v uuid.UUID) {
	o.AccountId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccountSessionAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountSessionAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccountSessionAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetLastUsed returns the LastUsed field value
func (o *AccountSessionAttributes) GetLastUsed() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUsed
}

// GetLastUsedOk returns a tuple with the LastUsed field value
// and a boolean to check if the value has been set.
func (o *AccountSessionAttributes) GetLastUsedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUsed, true
}

// SetLastUsed sets field value
func (o *AccountSessionAttributes) SetLastUsed(v time.Time) {
	o.LastUsed = v
}

func (o AccountSessionAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountSessionAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["last_used"] = o.LastUsed
	return toSerialize, nil
}

func (o *AccountSessionAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"created_at",
		"last_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountSessionAttributes := _AccountSessionAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountSessionAttributes)

	if err != nil {
		return err
	}

	*o = AccountSessionAttributes(varAccountSessionAttributes)

	return err
}

type NullableAccountSessionAttributes struct {
	value *AccountSessionAttributes
	isSet bool
}

func (v NullableAccountSessionAttributes) Get() *AccountSessionAttributes {
	return v.value
}

func (v *NullableAccountSessionAttributes) Set(val *AccountSessionAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountSessionAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountSessionAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountSessionAttributes(val *AccountSessionAttributes) *NullableAccountSessionAttributes {
	return &NullableAccountSessionAttributes{value: val, isSet: true}
}

func (v NullableAccountSessionAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountSessionAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


