/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AccountEmailDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountEmailDataAttributes{}

// AccountEmailDataAttributes struct for AccountEmailDataAttributes
type AccountEmailDataAttributes struct {
	// The email address associated with the account
	Email string `json:"email"`
	// The version number of the account record
	Version int32 `json:"version"`
	// Indicates whether the email address has been verified
	Verified bool `json:"verified"`
	// The date and time when the email information was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _AccountEmailDataAttributes AccountEmailDataAttributes

// NewAccountEmailDataAttributes instantiates a new AccountEmailDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountEmailDataAttributes(email string, version int32, verified bool, updatedAt time.Time) *AccountEmailDataAttributes {
	this := AccountEmailDataAttributes{}
	this.Email = email
	this.Version = version
	this.Verified = verified
	this.UpdatedAt = updatedAt
	return &this
}

// NewAccountEmailDataAttributesWithDefaults instantiates a new AccountEmailDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountEmailDataAttributesWithDefaults() *AccountEmailDataAttributes {
	this := AccountEmailDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *AccountEmailDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AccountEmailDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AccountEmailDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetVersion returns the Version field value
func (o *AccountEmailDataAttributes) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AccountEmailDataAttributes) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AccountEmailDataAttributes) SetVersion(v int32) {
	o.Version = v
}

// GetVerified returns the Verified field value
func (o *AccountEmailDataAttributes) GetVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value
// and a boolean to check if the value has been set.
func (o *AccountEmailDataAttributes) GetVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verified, true
}

// SetVerified sets field value
func (o *AccountEmailDataAttributes) SetVerified(v bool) {
	o.Verified = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AccountEmailDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountEmailDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AccountEmailDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o AccountEmailDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountEmailDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["version"] = o.Version
	toSerialize["verified"] = o.Verified
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *AccountEmailDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"version",
		"verified",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountEmailDataAttributes := _AccountEmailDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountEmailDataAttributes)

	if err != nil {
		return err
	}

	*o = AccountEmailDataAttributes(varAccountEmailDataAttributes)

	return err
}

type NullableAccountEmailDataAttributes struct {
	value *AccountEmailDataAttributes
	isSet bool
}

func (v NullableAccountEmailDataAttributes) Get() *AccountEmailDataAttributes {
	return v.value
}

func (v *NullableAccountEmailDataAttributes) Set(val *AccountEmailDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountEmailDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountEmailDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountEmailDataAttributes(val *AccountEmailDataAttributes) *NullableAccountEmailDataAttributes {
	return &NullableAccountEmailDataAttributes{value: val, isSet: true}
}

func (v NullableAccountEmailDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountEmailDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


