/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccountEmail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountEmail{}

// AccountEmail struct for AccountEmail
type AccountEmail struct {
	Data AccountEmailData `json:"data"`
}

type _AccountEmail AccountEmail

// NewAccountEmail instantiates a new AccountEmail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountEmail(data AccountEmailData) *AccountEmail {
	this := AccountEmail{}
	this.Data = data
	return &this
}

// NewAccountEmailWithDefaults instantiates a new AccountEmail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountEmailWithDefaults() *AccountEmail {
	this := AccountEmail{}
	return &this
}

// GetData returns the Data field value
func (o *AccountEmail) GetData() AccountEmailData {
	if o == nil {
		var ret AccountEmailData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AccountEmail) GetDataOk() (*AccountEmailData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AccountEmail) SetData(v AccountEmailData) {
	o.Data = v
}

func (o AccountEmail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountEmail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AccountEmail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountEmail := _AccountEmail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountEmail)

	if err != nil {
		return err
	}

	*o = AccountEmail(varAccountEmail)

	return err
}

type NullableAccountEmail struct {
	value *AccountEmail
	isSet bool
}

func (v NullableAccountEmail) Get() *AccountEmail {
	return v.value
}

func (v *NullableAccountEmail) Set(val *AccountEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountEmail(val *AccountEmail) *NullableAccountEmail {
	return &NullableAccountEmail{value: val, isSet: true}
}

func (v NullableAccountEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


