/*
netbill auth-svc API

swagger documentation for auth-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginByUsername type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginByUsername{}

// LoginByUsername struct for LoginByUsername
type LoginByUsername struct {
	Data LoginByUsernameData `json:"data"`
}

type _LoginByUsername LoginByUsername

// NewLoginByUsername instantiates a new LoginByUsername object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginByUsername(data LoginByUsernameData) *LoginByUsername {
	this := LoginByUsername{}
	this.Data = data
	return &this
}

// NewLoginByUsernameWithDefaults instantiates a new LoginByUsername object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginByUsernameWithDefaults() *LoginByUsername {
	this := LoginByUsername{}
	return &this
}

// GetData returns the Data field value
func (o *LoginByUsername) GetData() LoginByUsernameData {
	if o == nil {
		var ret LoginByUsernameData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *LoginByUsername) GetDataOk() (*LoginByUsernameData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *LoginByUsername) SetData(v LoginByUsernameData) {
	o.Data = v
}

func (o LoginByUsername) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginByUsername) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *LoginByUsername) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginByUsername := _LoginByUsername{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginByUsername)

	if err != nil {
		return err
	}

	*o = LoginByUsername(varLoginByUsername)

	return err
}

type NullableLoginByUsername struct {
	value *LoginByUsername
	isSet bool
}

func (v NullableLoginByUsername) Get() *LoginByUsername {
	return v.value
}

func (v *NullableLoginByUsername) Set(val *LoginByUsername) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginByUsername) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginByUsername) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginByUsername(val *LoginByUsername) *NullableLoginByUsername {
	return &NullableLoginByUsername{value: val, isSet: true}
}

func (v NullableLoginByUsername) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginByUsername) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


