// Code generated by mockery v2.53.6. DO NOT EDIT.

package account

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockTransaction is an autogenerated mock type for the transaction type
type mockTransaction struct {
	mock.Mock
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *mockTransaction) Transaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockTransaction creates a new instance of mockTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTransaction {
	mock := &mockTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
