// Code generated by mockery v2.53.6. DO NOT EDIT.

package account

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockPasswordCache is an autogenerated mock type for the passwordCache type
type mockPasswordCache struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, accountID
func (_m *mockPasswordCache) Delete(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, accountID
func (_m *mockPasswordCache) Get(ctx context.Context, accountID uuid.UUID) (models.AccountPassword, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.AccountPassword
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.AccountPassword, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.AccountPassword); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(models.AccountPassword)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, password
func (_m *mockPasswordCache) Set(ctx context.Context, password models.AccountPassword) error {
	ret := _m.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountPassword) error); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockPasswordCache creates a new instance of mockPasswordCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPasswordCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPasswordCache {
	mock := &mockPasswordCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
