// Code generated by mockery v2.53.6. DO NOT EDIT.

package account

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// mockMessenger is an autogenerated mock type for the messenger type
type mockMessenger struct {
	mock.Mock
}

// WriteAccountCreated provides a mock function with given fields: ctx, account, email
func (_m *mockMessenger) WriteAccountCreated(ctx context.Context, account models.Account, email models.AccountEmail) error {
	ret := _m.Called(ctx, account, email)

	if len(ret) == 0 {
		panic("no return value specified for WriteAccountCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Account, models.AccountEmail) error); ok {
		r0 = rf(ctx, account, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteAccountDeleted provides a mock function with given fields: ctx, account, email
func (_m *mockMessenger) WriteAccountDeleted(ctx context.Context, account models.Account, email models.AccountEmail) error {
	ret := _m.Called(ctx, account, email)

	if len(ret) == 0 {
		panic("no return value specified for WriteAccountDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Account, models.AccountEmail) error); ok {
		r0 = rf(ctx, account, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteAccountUsernameUpdated provides a mock function with given fields: ctx, account
func (_m *mockMessenger) WriteAccountUsernameUpdated(ctx context.Context, account models.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for WriteAccountUsernameUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockMessenger creates a new instance of mockMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMessenger {
	mock := &mockMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
