// Code generated by mockery v2.53.6. DO NOT EDIT.

package account

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// mockAuth is an autogenerated mock type for the auth type
type mockAuth struct {
	mock.Mock
}

// ValidateSession provides a mock function with given fields: ctx, actor
func (_m *mockAuth) ValidateSession(ctx context.Context, actor models.AccountActor) (models.Account, models.Session, error) {
	ret := _m.Called(ctx, actor)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSession")
	}

	var r0 models.Account
	var r1 models.Session
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountActor) (models.Account, models.Session, error)); ok {
		return rf(ctx, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AccountActor) models.Account); ok {
		r0 = rf(ctx, actor)
	} else {
		r0 = ret.Get(0).(models.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AccountActor) models.Session); ok {
		r1 = rf(ctx, actor)
	} else {
		r1 = ret.Get(1).(models.Session)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.AccountActor) error); ok {
		r2 = rf(ctx, actor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// newMockAuth creates a new instance of mockAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuth {
	mock := &mockAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
