// Code generated by mockery v2.53.6. DO NOT EDIT.

package account

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockAccountCache is an autogenerated mock type for the accountCache type
type mockAccountCache struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, accountID
func (_m *mockAccountCache) Delete(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, accountID
func (_m *mockAccountCache) Get(ctx context.Context, accountID uuid.UUID) (models.Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(models.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, account
func (_m *mockAccountCache) Set(ctx context.Context, account models.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockAccountCache creates a new instance of mockAccountCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAccountCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAccountCache {
	mock := &mockAccountCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
