// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	pagi "github.com/netbill/restkit/pagi"

	uuid "github.com/google/uuid"
)

// mockSessionRepo is an autogenerated mock type for the sessionRepo type
type mockSessionRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, sessionID, accountID, hashToken
func (_m *mockSessionRepo) Create(ctx context.Context, sessionID uuid.UUID, accountID uuid.UUID, hashToken string) (models.Session, error) {
	ret := _m.Called(ctx, sessionID, accountID, hashToken)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (models.Session, error)); ok {
		return rf(ctx, sessionID, accountID, hashToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) models.Session); ok {
		r0 = rf(ctx, sessionID, accountID, hashToken)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, sessionID, accountID, hashToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, sessionID
func (_m *mockSessionRepo) Delete(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteManyForAccount provides a mock function with given fields: ctx, accountID
func (_m *mockSessionRepo) DeleteManyForAccount(ctx context.Context, accountID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManyForAccount")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOneForAccount provides a mock function with given fields: ctx, accountID, sessionID
func (_m *mockSessionRepo) DeleteOneForAccount(ctx context.Context, accountID uuid.UUID, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, accountID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOneForAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, sessionID
func (_m *mockSessionRepo) GetByID(ctx context.Context, sessionID uuid.UUID) (models.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetForAccount provides a mock function with given fields: ctx, accountID, sessionID
func (_m *mockSessionRepo) GetForAccount(ctx context.Context, accountID uuid.UUID, sessionID uuid.UUID) (models.Session, error) {
	ret := _m.Called(ctx, accountID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetForAccount")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Session, error)); ok {
		return rf(ctx, accountID, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Session); ok {
		r0 = rf(ctx, accountID, sessionID)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, accountID, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListForAccount provides a mock function with given fields: ctx, accountID, opts
func (_m *mockSessionRepo) GetListForAccount(ctx context.Context, accountID uuid.UUID, opts ...ListSessionsOption) (pagi.Page[[]models.Session], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, accountID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetListForAccount")
	}

	var r0 pagi.Page[[]models.Session]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...ListSessionsOption) (pagi.Page[[]models.Session], error)); ok {
		return rf(ctx, accountID, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...ListSessionsOption) pagi.Page[[]models.Session]); ok {
		r0 = rf(ctx, accountID, opts...)
	} else {
		r0 = ret.Get(0).(pagi.Page[[]models.Session])
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...ListSessionsOption) error); ok {
		r1 = rf(ctx, accountID, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetToken provides a mock function with given fields: ctx, sessionID
func (_m *mockSessionRepo) GetToken(ctx context.Context, sessionID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateToken provides a mock function with given fields: ctx, sessionID, token
func (_m *mockSessionRepo) UpdateToken(ctx context.Context, sessionID uuid.UUID, token string) (models.Session, error) {
	ret := _m.Called(ctx, sessionID, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateToken")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (models.Session, error)); ok {
		return rf(ctx, sessionID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) models.Session); ok {
		r0 = rf(ctx, sessionID, token)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, sessionID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockSessionRepo creates a new instance of mockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionRepo {
	mock := &mockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
