// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockBus is an autogenerated mock type for the bus type
type mockBus struct {
	mock.Mock
}

// PublishQRToken provides a mock function with given fields: ctx, key, payload
func (_m *mockBus) PublishQRToken(ctx context.Context, key string, payload []byte) error {
	ret := _m.Called(ctx, key, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishQRToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, key, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockBus creates a new instance of mockBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBus {
	mock := &mockBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
