// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// mockEmailRepo is an autogenerated mock type for the emailRepo type
type mockEmailRepo struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *mockEmailRepo) GetByEmail(ctx context.Context, email string) (models.UserEmail, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 models.UserEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.UserEmail, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.UserEmail); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(models.UserEmail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockEmailRepo creates a new instance of mockEmailRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEmailRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEmailRepo {
	mock := &mockEmailRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
