// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// mockQrRepo is an autogenerated mock type for the qrRepo type
type mockQrRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, token
func (_m *mockQrRepo) Get(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, token, status, ttl
func (_m *mockQrRepo) Set(ctx context.Context, token string, status string, ttl time.Duration) error {
	ret := _m.Called(ctx, token, status, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, token, status, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockQrRepo creates a new instance of mockQrRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockQrRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockQrRepo {
	mock := &mockQrRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
