// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	tokens "github.com/netbill/restkit/tokens"

	uuid "github.com/google/uuid"
)

// mockTokenManager is an autogenerated mock type for the tokenManager type
type mockTokenManager struct {
	mock.Mock
}

// GenerateAccess provides a mock function with given fields: account, sessionID
func (_m *mockTokenManager) GenerateAccess(account models.Account, sessionID uuid.UUID) (string, error) {
	ret := _m.Called(account, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccess")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Account, uuid.UUID) (string, error)); ok {
		return rf(account, sessionID)
	}
	if rf, ok := ret.Get(0).(func(models.Account, uuid.UUID) string); ok {
		r0 = rf(account, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Account, uuid.UUID) error); ok {
		r1 = rf(account, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateRefresh provides a mock function with given fields: account, sessionID
func (_m *mockTokenManager) GenerateRefresh(account models.Account, sessionID uuid.UUID) (string, error) {
	ret := _m.Called(account, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefresh")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Account, uuid.UUID) (string, error)); ok {
		return rf(account, sessionID)
	}
	if rf, ok := ret.Get(0).(func(models.Account, uuid.UUID) string); ok {
		r0 = rf(account, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(models.Account, uuid.UUID) error); ok {
		r1 = rf(account, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HashRefresh provides a mock function with given fields: token
func (_m *mockTokenManager) HashRefresh(token string) (string, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for HashRefresh")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseAccountAuthAccess provides a mock function with given fields: token
func (_m *mockTokenManager) ParseAccountAuthAccess(token string) (tokens.AccountAuthClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccountAuthAccess")
	}

	var r0 tokens.AccountAuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (tokens.AccountAuthClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) tokens.AccountAuthClaims); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(tokens.AccountAuthClaims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseAccountAuthRefresh provides a mock function with given fields: token
func (_m *mockTokenManager) ParseAccountAuthRefresh(token string) (tokens.AccountAuthClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccountAuthRefresh")
	}

	var r0 tokens.AccountAuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (tokens.AccountAuthClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) tokens.AccountAuthClaims); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(tokens.AccountAuthClaims)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockTokenManager creates a new instance of mockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTokenManager {
	mock := &mockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
