// Code generated by mockery v2.53.6. DO NOT EDIT.

package session

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockSessionsCache is an autogenerated mock type for the sessionsCache type
type mockSessionsCache struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, sessionID
func (_m *mockSessionsCache) Delete(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, sessionID
func (_m *mockSessionsCache) Get(ctx context.Context, sessionID uuid.UUID) (models.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, session
func (_m *mockSessionsCache) Set(ctx context.Context, session models.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockSessionsCache creates a new instance of mockSessionsCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionsCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionsCache {
	mock := &mockSessionsCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
