// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: session.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionDeletedFilter filters sessions by their deletion status.
type SessionDeletedFilter int32

const (
	// Return both active and deleted sessions. Default.
	SessionDeletedFilter_SESSION_DELETED_FILTER_ALL SessionDeletedFilter = 0
	// Return only active (non-deleted) sessions.
	SessionDeletedFilter_SESSION_DELETED_FILTER_ACTIVE SessionDeletedFilter = 1
	// Return only deleted (terminated) sessions.
	SessionDeletedFilter_SESSION_DELETED_FILTER_DELETED SessionDeletedFilter = 2
)

// Enum value maps for SessionDeletedFilter.
var (
	SessionDeletedFilter_name = map[int32]string{
		0: "SESSION_DELETED_FILTER_ALL",
		1: "SESSION_DELETED_FILTER_ACTIVE",
		2: "SESSION_DELETED_FILTER_DELETED",
	}
	SessionDeletedFilter_value = map[string]int32{
		"SESSION_DELETED_FILTER_ALL":     0,
		"SESSION_DELETED_FILTER_ACTIVE":  1,
		"SESSION_DELETED_FILTER_DELETED": 2,
	}
)

func (x SessionDeletedFilter) Enum() *SessionDeletedFilter {
	p := new(SessionDeletedFilter)
	*p = x
	return p
}

func (x SessionDeletedFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionDeletedFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[0].Descriptor()
}

func (SessionDeletedFilter) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[0]
}

func (x SessionDeletedFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionDeletedFilter.Descriptor instead.
func (SessionDeletedFilter) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

// SessionLastUsedOrder controls the sort direction of the last_used field.
type SessionLastUsedOrder int32

const (
	// Most recently used first. Default.
	SessionLastUsedOrder_SESSION_LAST_USED_ORDER_DESC SessionLastUsedOrder = 0
	// Least recently used first.
	SessionLastUsedOrder_SESSION_LAST_USED_ORDER_ASC SessionLastUsedOrder = 1
)

// Enum value maps for SessionLastUsedOrder.
var (
	SessionLastUsedOrder_name = map[int32]string{
		0: "SESSION_LAST_USED_ORDER_DESC",
		1: "SESSION_LAST_USED_ORDER_ASC",
	}
	SessionLastUsedOrder_value = map[string]int32{
		"SESSION_LAST_USED_ORDER_DESC": 0,
		"SESSION_LAST_USED_ORDER_ASC":  1,
	}
)

func (x SessionLastUsedOrder) Enum() *SessionLastUsedOrder {
	p := new(SessionLastUsedOrder)
	*p = x
	return p
}

func (x SessionLastUsedOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionLastUsedOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[1].Descriptor()
}

func (SessionLastUsedOrder) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[1]
}

func (x SessionLastUsedOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionLastUsedOrder.Descriptor instead.
func (SessionLastUsedOrder) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

type LoginByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByEmailRequest) Reset() {
	*x = LoginByEmailRequest{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByEmailRequest) ProtoMessage() {}

func (x *LoginByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByEmailRequest.ProtoReflect.Descriptor instead.
func (*LoginByEmailRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *LoginByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginByEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByUsernameRequest) Reset() {
	*x = LoginByUsernameRequest{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByUsernameRequest) ProtoMessage() {}

func (x *LoginByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByUsernameRequest.ProtoReflect.Descriptor instead.
func (*LoginByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *LoginByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginByUsernameRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginByGoogleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Google ID token obtained from the Google OAuth2 flow.
	IdToken       string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByGoogleRequest) Reset() {
	*x = LoginByGoogleRequest{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByGoogleRequest) ProtoMessage() {}

func (x *LoginByGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByGoogleRequest.ProtoReflect.Descriptor instead.
func (*LoginByGoogleRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *LoginByGoogleRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

// LoginResponse is returned by all login and refresh methods.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokensPair            `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetTokens() *TokensPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refresh token from a previous LoginResponse or RefreshResponse.
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetMySessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the target session.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySessionRequest) Reset() {
	*x = GetMySessionRequest{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySessionRequest) ProtoMessage() {}

func (x *GetMySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySessionRequest.ProtoReflect.Descriptor instead.
func (*GetMySessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetMySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetMySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySessionResponse) Reset() {
	*x = GetMySessionResponse{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySessionResponse) ProtoMessage() {}

func (x *GetMySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySessionResponse.ProtoReflect.Descriptor instead.
func (*GetMySessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

func (x *GetMySessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetMySessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters. Defaults: page=1, per_page=20.
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Filter sessions by active/deleted status. Defaults to ALL.
	Filter SessionDeletedFilter `protobuf:"varint,2,opt,name=filter,proto3,enum=auth.v1.SessionDeletedFilter" json:"filter,omitempty"`
	// Sort order by last_used timestamp. Defaults to DESC.
	Order         SessionLastUsedOrder `protobuf:"varint,3,opt,name=order,proto3,enum=auth.v1.SessionLastUsedOrder" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySessionsRequest) Reset() {
	*x = GetMySessionsRequest{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySessionsRequest) ProtoMessage() {}

func (x *GetMySessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySessionsRequest.ProtoReflect.Descriptor instead.
func (*GetMySessionsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{7}
}

func (x *GetMySessionsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetMySessionsRequest) GetFilter() SessionDeletedFilter {
	if x != nil {
		return x.Filter
	}
	return SessionDeletedFilter_SESSION_DELETED_FILTER_ALL
}

func (x *GetMySessionsRequest) GetOrder() SessionLastUsedOrder {
	if x != nil {
		return x.Order
	}
	return SessionLastUsedOrder_SESSION_LAST_USED_ORDER_DESC
}

type GetMySessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySessionsResponse) Reset() {
	*x = GetMySessionsResponse{}
	mi := &file_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySessionsResponse) ProtoMessage() {}

func (x *GetMySessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySessionsResponse.ProtoReflect.Descriptor instead.
func (*GetMySessionsResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{8}
}

func (x *GetMySessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *GetMySessionsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{9}
}

type DeleteMySessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the session to terminate.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMySessionRequest) Reset() {
	*x = DeleteMySessionRequest{}
	mi := &file_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMySessionRequest) ProtoMessage() {}

func (x *DeleteMySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMySessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteMySessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteMySessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMySessionsRequest) Reset() {
	*x = DeleteMySessionsRequest{}
	mi := &file_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMySessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMySessionsRequest) ProtoMessage() {}

func (x *DeleteMySessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMySessionsRequest.ProtoReflect.Descriptor instead.
func (*DeleteMySessionsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{11}
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\aauth.v1\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"G\n" +
	"\x13LoginByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"P\n" +
	"\x16LoginByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"1\n" +
	"\x14LoginByGoogleRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"<\n" +
	"\rLoginResponse\x12+\n" +
	"\x06tokens\x18\x01 \x01(\v2\x13.auth.v1.TokensPairR\x06tokens\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\x13GetMySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"B\n" +
	"\x14GetMySessionResponse\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.auth.v1.SessionR\asession\"\xb7\x01\n" +
	"\x14GetMySessionsRequest\x123\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x13.auth.v1.PaginationR\n" +
	"pagination\x125\n" +
	"\x06filter\x18\x02 \x01(\x0e2\x1d.auth.v1.SessionDeletedFilterR\x06filter\x123\n" +
	"\x05order\x18\x03 \x01(\x0e2\x1d.auth.v1.SessionLastUsedOrderR\x05order\"u\n" +
	"\x15GetMySessionsResponse\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.auth.v1.SessionR\bsessions\x12.\n" +
	"\tpage_info\x18\x02 \x01(\v2\x11.auth.v1.PageInfoR\bpageInfo\"\x0f\n" +
	"\rLogoutRequest\"7\n" +
	"\x16DeleteMySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x19\n" +
	"\x17DeleteMySessionsRequest*}\n" +
	"\x14SessionDeletedFilter\x12\x1e\n" +
	"\x1aSESSION_DELETED_FILTER_ALL\x10\x00\x12!\n" +
	"\x1dSESSION_DELETED_FILTER_ACTIVE\x10\x01\x12\"\n" +
	"\x1eSESSION_DELETED_FILTER_DELETED\x10\x02*Y\n" +
	"\x14SessionLastUsedOrder\x12 \n" +
	"\x1cSESSION_LAST_USED_ORDER_DESC\x10\x00\x12\x1f\n" +
	"\x1bSESSION_LAST_USED_ORDER_ASC\x10\x012\x97\x05\n" +
	"\x0eSessionService\x12D\n" +
	"\fLoginByEmail\x12\x1c.auth.v1.LoginByEmailRequest\x1a\x16.auth.v1.LoginResponse\x12J\n" +
	"\x0fLoginByUsername\x12\x1f.auth.v1.LoginByUsernameRequest\x1a\x16.auth.v1.LoginResponse\x12F\n" +
	"\rLoginByGoogle\x12\x1d.auth.v1.LoginByGoogleRequest\x1a\x16.auth.v1.LoginResponse\x12:\n" +
	"\aRefresh\x12\x17.auth.v1.RefreshRequest\x1a\x16.auth.v1.LoginResponse\x12K\n" +
	"\fGetMySession\x12\x1c.auth.v1.GetMySessionRequest\x1a\x1d.auth.v1.GetMySessionResponse\x12N\n" +
	"\rGetMySessions\x12\x1d.auth.v1.GetMySessionsRequest\x1a\x1e.auth.v1.GetMySessionsResponse\x128\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0fDeleteMySession\x12\x1f.auth.v1.DeleteMySessionRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x10DeleteMySessions\x12 .auth.v1.DeleteMySessionsRequest\x1a\x16.google.protobuf.EmptyB)Z'github.com/netbill/auth-svc/proto/pb;pbb\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_session_proto_goTypes = []any{
	(SessionDeletedFilter)(0),       // 0: auth.v1.SessionDeletedFilter
	(SessionLastUsedOrder)(0),       // 1: auth.v1.SessionLastUsedOrder
	(*LoginByEmailRequest)(nil),     // 2: auth.v1.LoginByEmailRequest
	(*LoginByUsernameRequest)(nil),  // 3: auth.v1.LoginByUsernameRequest
	(*LoginByGoogleRequest)(nil),    // 4: auth.v1.LoginByGoogleRequest
	(*LoginResponse)(nil),           // 5: auth.v1.LoginResponse
	(*RefreshRequest)(nil),          // 6: auth.v1.RefreshRequest
	(*GetMySessionRequest)(nil),     // 7: auth.v1.GetMySessionRequest
	(*GetMySessionResponse)(nil),    // 8: auth.v1.GetMySessionResponse
	(*GetMySessionsRequest)(nil),    // 9: auth.v1.GetMySessionsRequest
	(*GetMySessionsResponse)(nil),   // 10: auth.v1.GetMySessionsResponse
	(*LogoutRequest)(nil),           // 11: auth.v1.LogoutRequest
	(*DeleteMySessionRequest)(nil),  // 12: auth.v1.DeleteMySessionRequest
	(*DeleteMySessionsRequest)(nil), // 13: auth.v1.DeleteMySessionsRequest
	(*TokensPair)(nil),              // 14: auth.v1.TokensPair
	(*Session)(nil),                 // 15: auth.v1.Session
	(*Pagination)(nil),              // 16: auth.v1.Pagination
	(*PageInfo)(nil),                // 17: auth.v1.PageInfo
	(*emptypb.Empty)(nil),           // 18: google.protobuf.Empty
}
var file_session_proto_depIdxs = []int32{
	14, // 0: auth.v1.LoginResponse.tokens:type_name -> auth.v1.TokensPair
	15, // 1: auth.v1.GetMySessionResponse.session:type_name -> auth.v1.Session
	16, // 2: auth.v1.GetMySessionsRequest.pagination:type_name -> auth.v1.Pagination
	0,  // 3: auth.v1.GetMySessionsRequest.filter:type_name -> auth.v1.SessionDeletedFilter
	1,  // 4: auth.v1.GetMySessionsRequest.order:type_name -> auth.v1.SessionLastUsedOrder
	15, // 5: auth.v1.GetMySessionsResponse.sessions:type_name -> auth.v1.Session
	17, // 6: auth.v1.GetMySessionsResponse.page_info:type_name -> auth.v1.PageInfo
	2,  // 7: auth.v1.SessionService.LoginByEmail:input_type -> auth.v1.LoginByEmailRequest
	3,  // 8: auth.v1.SessionService.LoginByUsername:input_type -> auth.v1.LoginByUsernameRequest
	4,  // 9: auth.v1.SessionService.LoginByGoogle:input_type -> auth.v1.LoginByGoogleRequest
	6,  // 10: auth.v1.SessionService.Refresh:input_type -> auth.v1.RefreshRequest
	7,  // 11: auth.v1.SessionService.GetMySession:input_type -> auth.v1.GetMySessionRequest
	9,  // 12: auth.v1.SessionService.GetMySessions:input_type -> auth.v1.GetMySessionsRequest
	11, // 13: auth.v1.SessionService.Logout:input_type -> auth.v1.LogoutRequest
	12, // 14: auth.v1.SessionService.DeleteMySession:input_type -> auth.v1.DeleteMySessionRequest
	13, // 15: auth.v1.SessionService.DeleteMySessions:input_type -> auth.v1.DeleteMySessionsRequest
	5,  // 16: auth.v1.SessionService.LoginByEmail:output_type -> auth.v1.LoginResponse
	5,  // 17: auth.v1.SessionService.LoginByUsername:output_type -> auth.v1.LoginResponse
	5,  // 18: auth.v1.SessionService.LoginByGoogle:output_type -> auth.v1.LoginResponse
	5,  // 19: auth.v1.SessionService.Refresh:output_type -> auth.v1.LoginResponse
	8,  // 20: auth.v1.SessionService.GetMySession:output_type -> auth.v1.GetMySessionResponse
	10, // 21: auth.v1.SessionService.GetMySessions:output_type -> auth.v1.GetMySessionsResponse
	18, // 22: auth.v1.SessionService.Logout:output_type -> google.protobuf.Empty
	18, // 23: auth.v1.SessionService.DeleteMySession:output_type -> google.protobuf.Empty
	18, // 24: auth.v1.SessionService.DeleteMySessions:output_type -> google.protobuf.Empty
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		EnumInfos:         file_session_proto_enumTypes,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
