// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"

	models "github.com/netbill/auth-svc/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockSessionRepo is an autogenerated mock type for the sessionRepo type
type mockSessionRepo struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, sessionID
func (_m *mockSessionRepo) GetByID(ctx context.Context, sessionID uuid.UUID) (models.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(models.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockSessionRepo creates a new instance of mockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionRepo {
	mock := &mockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
